ns-3: ns3::SinkHelper Class Reference
ns3::SinkHelper Class Reference
Application-helper
Helper class for the creation of Sink applications.
#include "sink-helper.h"
Public Member Functions
SinkHelper ()
Default constructor.
SinkHelper (uint16_t numnodes, Ptr< OutputManager > outputManager, Ptr< OnionValidator > onionValidator, uint16_t *m_onionPathLengths)
Constructor with attributes to set basic attributes of the sink node.
~SinkHelper ()
Default constructor.
ApplicationContainer Install (NodeContainer c) const
Ptr< Application > InstallPriv (Ptr< Node > node) const
void SetAttribute (std::string name, const AttributeValue &value)
Setter of individual attributes.
Static Public Member Functions
static TypeId GetTypeId (void)
Register this type.
Private Attributes
ObjectFactory m_factory
factory object
uint16_t m_numnodes
Number of sensor nodes in the network.
uint16_t m_onionTimeout
A watchdog timer set to abort onion messagess, if the timer elepses before the onion returns back to the sink node.
Ptr< OnionValidator > m_onionValidator
Manage onions and when to abort them.
Ptr< OutputManager > m_outputManager
Manage the output of the simulation.
Detailed Description
Helper class for the creation of Sink applications.
Definition at line 66 of file sink-helper.h.
Constructor & Destructor Documentation
SinkHelper() [1/2]
ns3::SinkHelper::SinkHelper ()
Default constructor.
Definition at line 39 of file sink-helper.cc.
References m_factory.
SinkHelper() [2/2]
ns3::SinkHelper::SinkHelper (uint16_t numnodes, Ptr< OutputManager > outputManager, Ptr< OnionValidator > onionValidator, uint16_t * m_onionPathLengths)
Constructor with attributes to set basic attributes of the sink node.
Definition at line 44 of file sink-helper.cc.
References m_factory, m_numnodes, m_onionValidator, and m_outputManager.
~SinkHelper()
ns3::SinkHelper::~SinkHelper ()
Default constructor.
Definition at line 54 of file sink-helper.cc.
Member Function Documentation
GetTypeId()
TypeId ns3::SinkHelper::GetTypeId (void) static
Register this type.
Returns
The object TypeId.
Definition at line 32 of file sink-helper.cc.
Install()
ApplicationContainer ns3::SinkHelper::Install (NodeContainer c) const
Definition at line 65 of file sink-helper.cc.
References InstallPriv().
Referenced by WsnConstructor::InstallApplications().
InstallPriv()
Ptr< Application > ns3::SinkHelper::InstallPriv (Ptr< Node > node) const
Definition at line 77 of file sink-helper.cc.
References m_factory.
Referenced by Install().
SetAttribute()
void ns3::SinkHelper::SetAttribute (std::string name, const AttributeValue & value)
Setter of individual attributes.
Definition at line 59 of file sink-helper.cc.
References m_factory.
Member Data Documentation
m_factory
ObjectFactory ns3::SinkHelper::m_factory private
factory object
Definition at line 124 of file sink-helper.h.
Referenced by InstallPriv(), SetAttribute(), and SinkHelper().
m_numnodes
uint16_t ns3::SinkHelper::m_numnodes private
Number of sensor nodes in the network.
Definition at line 123 of file sink-helper.h.
Referenced by SinkHelper().
m_onionTimeout
uint16_t ns3::SinkHelper::m_onionTimeout private
A watchdog timer set to abort onion messagess, if the timer elepses before the onion returns back to the sink node.
Definition at line 128 of file sink-helper.h.
m_onionValidator
Ptr<OnionValidator> ns3::SinkHelper::m_onionValidator private
Manage onions and when to abort them.
Definition at line 126 of file sink-helper.h.
Referenced by SinkHelper().
m_outputManager
Ptr<OutputManager> ns3::SinkHelper::m_outputManager private
Manage the output of the simulation.
Definition at line 125 of file sink-helper.h.
Referenced by SinkHelper().
The documentation for this class was generated from the following files:
src/onion_routing_wsn/helper/sink-helper.h
src/onion_routing_wsn/helper/sink-helper.cc