ns-3: ns3::SerializationWrapper Class Reference
ns3::SerializationWrapper Class Reference
Serialization
Class for the serialization-deserialization of the messagess to send in packets.
#include "serializationwrapper.h"
Public Member Functions
SerializationWrapper ()
Default constructor.
SerializationWrapper (protomessage::ProtoPacket message)
Constructor with argument.
virtual ~SerializationWrapper ()
virtual uint32_t Deserialize (Buffer::Iterator start)
deserialize the data
void GetData (protomessage::ProtoPacket *message)
Getter of the data in the protocol header.
virtual TypeId GetInstanceTypeId (void) const
virtual uint32_t GetSerializedSize (void) const
compute the serialized size of the data
virtual void Print (std::ostream &os) const
dummy printing of the serialized data
virtual void Serialize (Buffer::Iterator start) const
serialize the data
void SetData (protomessage::ProtoPacket message)
Setter of the data in the protocol header.
Static Public Member Functions
static TypeId GetTypeId (void)
Register this type.
Public Attributes
uint8_t * m_data
the serialized data
int m_dataSize = 0
holds the size of the serialized data in bytes
Detailed Description
Class for the serialization-deserialization of the messagess to send in packets.
Definition at line 54 of file serializationwrapper.h.
Constructor & Destructor Documentation
SerializationWrapper() [1/2]
ns3::SerializationWrapper::SerializationWrapper ()
Default constructor.
Definition at line 47 of file serializationwrapper.cc.
~SerializationWrapper()
ns3::SerializationWrapper::~SerializationWrapper () virtual
Definition at line 51 of file serializationwrapper.cc.
References m_data.
SerializationWrapper() [2/2]
ns3::SerializationWrapper::SerializationWrapper (protomessage::ProtoPacket message)
Constructor with argument.
Parameters
[in] message the protobuff object containing the data to transmit
Definition at line 81 of file serializationwrapper.cc.
References SetData().
Member Function Documentation
Deserialize()
uint32_t ns3::SerializationWrapper::Deserialize (Buffer::Iterator start) virtual
deserialize the data
Parameters
[in,out] start an iterator which points to where the data should read from.
Returns
the number of bytes read.
Definition at line 105 of file serializationwrapper.cc.
References m_data, and m_dataSize.
GetData()
void ns3::SerializationWrapper::GetData (protomessage::ProtoPacket * message)
Getter of the data in the protocol header.
Parameters
[in,out] message pointer to the protobuff object for storing data
Definition at line 75 of file serializationwrapper.cc.
References m_data, and m_dataSize.
Referenced by ns3::SensorNode::ReceivePacket(), and ns3::Sink::ReceivePacket().
GetInstanceTypeId()
TypeId ns3::SerializationWrapper::GetInstanceTypeId (void) const virtual
Returns
The object TypeId.
Definition at line 42 of file serializationwrapper.cc.
References GetTypeId().
GetSerializedSize()
uint32_t ns3::SerializationWrapper::GetSerializedSize (void) const virtual
compute the serialized size of the data
Returns
return the size of the serialized data in bytes
Definition at line 87 of file serializationwrapper.cc.
References m_dataSize.
GetTypeId()
TypeId ns3::SerializationWrapper::GetTypeId (void) static
Register this type.
Returns
The object TypeId.
Definition at line 31 of file serializationwrapper.cc.
Referenced by GetInstanceTypeId().
Print()
void ns3::SerializationWrapper::Print (std::ostream & os) const virtual
dummy printing of the serialized data
Definition at line 123 of file serializationwrapper.cc.
Serialize()
void ns3::SerializationWrapper::Serialize (Buffer::Iterator start) const virtual
serialize the data
Parameters
[in,out] start an iterator which points to where the data should be written.
Definition at line 98 of file serializationwrapper.cc.
References m_data, and m_dataSize.
SetData()
void ns3::SerializationWrapper::SetData (protomessage::ProtoPacket message)
Setter of the data in the protocol header.
Parameters
[in] message the protobuff object containing the data to transmit
Definition at line 58 of file serializationwrapper.cc.
References protomessage::ProtoPacket::ByteSizeLong(), m_data, and m_dataSize.
Referenced by ns3::SensorNode::ReceivePacket(), and SerializationWrapper().
Member Data Documentation
m_data
uint8_t* ns3::SerializationWrapper::m_data
the serialized data
Definition at line 142 of file serializationwrapper.h.
Referenced by Deserialize(), GetData(), Serialize(), SetData(), and ~SerializationWrapper().
m_dataSize
int ns3::SerializationWrapper::m_dataSize = 0
holds the size of the serialized data in bytes
Definition at line 140 of file serializationwrapper.h.
Referenced by Deserialize(), GetData(), GetSerializedSize(), Serialize(), and SetData().
The documentation for this class was generated from the following files:
src/onion_routing_wsn/protocol/serializationwrapper.h
src/onion_routing_wsn/protocol/serializationwrapper.cc