ns-3: ns3::SegmentNum Class Reference
ns3::SegmentNum Class Reference
Serialization
Class for adding a tag to packets used to track different segments of packets packets are fragmented due to small MSS Just implementing methods from ns3 class ns3::Tag.
#include "segmentnum.h"
Public Member Functions
SegmentNum ()
SegmentNum (uint32_t seg_num)
~SegmentNum ()
virtual void Deserialize (TagBuffer i)
virtual TypeId GetInstanceTypeId (void) const
uint32_t GetSegNum ()
virtual uint32_t GetSerializedSize (void) const
virtual void Print (std::ostream &os) const
virtual void Serialize (TagBuffer i) const
void SetSegNum (uint32_t seg_num)
Static Public Member Functions
static TypeId GetTypeId (void)
Public Attributes
uint32_t s_num
Detailed Description
Class for adding a tag to packets used to track different segments of packets packets are fragmented due to small MSS Just implementing methods from ns3 class ns3::Tag.
Definition at line 41 of file segmentnum.h.
Constructor & Destructor Documentation
SegmentNum() [1/2]
ns3::SegmentNum::SegmentNum ()
Definition at line 48 of file segmentnum.cc.
References s_num.
SegmentNum() [2/2]
ns3::SegmentNum::SegmentNum (uint32_t seg_num)
Definition at line 53 of file segmentnum.cc.
References s_num.
~SegmentNum()
ns3::SegmentNum::~SegmentNum ()
Definition at line 58 of file segmentnum.cc.
Member Function Documentation
Deserialize()
void ns3::SegmentNum::Deserialize (TagBuffer i) virtual
Definition at line 82 of file segmentnum.cc.
References s_num.
GetInstanceTypeId()
TypeId ns3::SegmentNum::GetInstanceTypeId (void) const virtual
Definition at line 42 of file segmentnum.cc.
References GetTypeId().
GetSegNum()
uint32_t ns3::SegmentNum::GetSegNum ()
Definition at line 60 of file segmentnum.cc.
References s_num.
Referenced by ns3::Wsn_node::RecvSeg().
GetSerializedSize()
uint32_t ns3::SegmentNum::GetSerializedSize (void) const virtual
Definition at line 72 of file segmentnum.cc.
GetTypeId()
TypeId ns3::SegmentNum::GetTypeId (void) static
Definition at line 31 of file segmentnum.cc.
Referenced by GetInstanceTypeId().
Print()
void ns3::SegmentNum::Print (std::ostream & os) const virtual
Definition at line 87 of file segmentnum.cc.
References s_num.
Serialize()
void ns3::SegmentNum::Serialize (TagBuffer i) const virtual
Definition at line 77 of file segmentnum.cc.
References s_num.
SetSegNum()
void ns3::SegmentNum::SetSegNum (uint32_t seg_num)
Definition at line 65 of file segmentnum.cc.
References s_num.
Member Data Documentation
s_num
uint32_t ns3::SegmentNum::s_num
Definition at line 61 of file segmentnum.h.
Referenced by Deserialize(), GetSegNum(), Print(), SegmentNum(), Serialize(), and SetSegNum().
The documentation for this class was generated from the following files:
src/onion_routing_wsn/protocol/segmentnum.h
src/onion_routing_wsn/protocol/segmentnum.cc