ns-3: protomessage::ProtoPacket Class Reference
protomessage::ProtoPacket Class Reference final
#include "proto-packet.pb.h"
Classes
class _Internal
Public Types
enum : int { kHShakeFieldNumber = 1, kOHeadFieldNumber = 2, kOBodyFieldNumber = 3 }
typedef ProtoPacket_Handshake Handshake
typedef ProtoPacket_OnionBody OnionBody
typedef ProtoPacket_OnionHead OnionHead
Public Member Functions
ProtoPacket ()
constexpr ProtoPacket (::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
ProtoPacket (const ProtoPacket &from)
ProtoPacket (ProtoPacket &&from) noexcept
~ProtoPacket () override
const char * _InternalParse (const char *ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext *ctx) final
uint8_t * _InternalSerialize (uint8_t *target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream *stream) const final
size_t ByteSizeLong () const final
PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear () final
void clear_h_shake ()
void clear_o_body ()
void clear_o_head ()
void CopyFrom (const ProtoPacket &from)
int GetCachedSize () const final
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData * GetClassData () const final
::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata () const final
const ::protomessage::ProtoPacket_Handshake & h_shake () const
bool has_h_shake () const
bool has_o_body () const
bool has_o_head () const
bool IsInitialized () const final
void MergeFrom (const ProtoPacket &from)
::protomessage::ProtoPacket_Handshake * mutable_h_shake ()
::protomessage::ProtoPacket_OnionBody * mutable_o_body ()
::protomessage::ProtoPacket_OnionHead * mutable_o_head ()
ProtoPacket * New (::PROTOBUF_NAMESPACE_ID::Arena *arena=nullptr) const final
const ::protomessage::ProtoPacket_OnionBody & o_body () const
const ::protomessage::ProtoPacket_OnionHead & o_head () const
ProtoPacket & operator= (const ProtoPacket &from)
ProtoPacket & operator= (ProtoPacket &&from) noexcept
PROTOBUF_NODISCARD ::protomessage::ProtoPacket_Handshake * release_h_shake ()
PROTOBUF_NODISCARD ::protomessage::ProtoPacket_OnionBody * release_o_body ()
PROTOBUF_NODISCARD ::protomessage::ProtoPacket_OnionHead * release_o_head ()
void set_allocated_h_shake (::protomessage::ProtoPacket_Handshake *h_shake)
void set_allocated_o_body (::protomessage::ProtoPacket_OnionBody *o_body)
void set_allocated_o_head (::protomessage::ProtoPacket_OnionHead *o_head)
void Swap (ProtoPacket *other)
::protomessage::ProtoPacket_Handshake * unsafe_arena_release_h_shake ()
::protomessage::ProtoPacket_OnionBody * unsafe_arena_release_o_body ()
::protomessage::ProtoPacket_OnionHead * unsafe_arena_release_o_head ()
void unsafe_arena_set_allocated_h_shake (::protomessage::ProtoPacket_Handshake *h_shake)
void unsafe_arena_set_allocated_o_body (::protomessage::ProtoPacket_OnionBody *o_body)
void unsafe_arena_set_allocated_o_head (::protomessage::ProtoPacket_OnionHead *o_head)
void UnsafeArenaSwap (ProtoPacket *other)
Static Public Member Functions
static const ProtoPacket & default_instance ()
static const ::PROTOBUF_NAMESPACE_ID::Descriptor * descriptor ()
static const ::PROTOBUF_NAMESPACE_ID::Descriptor * GetDescriptor ()
static const ::PROTOBUF_NAMESPACE_ID::Reflection * GetReflection ()
static const ProtoPacket * internal_default_instance ()
Static Public Attributes
static const ClassData _class_data_
static constexpr int kIndexInFileMessages
Protected Member Functions
ProtoPacket (::PROTOBUF_NAMESPACE_ID::Arena *arena, bool is_message_owned=false)
Private Types
typedef void DestructorSkippable_
typedef void InternalArenaConstructable_
Private Member Functions
const ::protomessage::ProtoPacket_Handshake & _internal_h_shake () const
bool _internal_has_h_shake () const
bool _internal_has_o_body () const
bool _internal_has_o_head () const
::protomessage::ProtoPacket_Handshake * _internal_mutable_h_shake ()
::protomessage::ProtoPacket_OnionBody * _internal_mutable_o_body ()
::protomessage::ProtoPacket_OnionHead * _internal_mutable_o_head ()
const ::protomessage::ProtoPacket_OnionBody & _internal_o_body () const
const ::protomessage::ProtoPacket_OnionHead & _internal_o_head () const
void InternalSwap (ProtoPacket *other)
void RegisterArenaDtor (::PROTOBUF_NAMESPACE_ID::Arena *arena)
void SetCachedSize (int size) const final
void SharedCtor ()
void SharedDtor ()
Static Private Member Functions
static void ArenaDtor (void *object)
::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName ()
static void MergeImpl (::PROTOBUF_NAMESPACE_ID::Message *to, const ::PROTOBUF_NAMESPACE_ID::Message &from)
Private Attributes
mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_
::PROTOBUF_NAMESPACE_ID::internal::HasBits< 1 > _has_bits_
::protomessage::ProtoPacket_Handshake * h_shake_
::protomessage::ProtoPacket_OnionBody * o_body_
::protomessage::ProtoPacket_OnionHead * o_head_
Friends
template<typename T >
class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper
class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata
struct ::TableStruct_proto_2dpacket_2eproto
void swap (ProtoPacket &a, ProtoPacket &b)
Detailed Description
Definition at line 598 of file proto-packet.pb.h.
Member Typedef Documentation
DestructorSkippable_
typedef void protomessage::ProtoPacket::DestructorSkippable_ private
Definition at line 788 of file proto-packet.pb.h.
Handshake
typedef ProtoPacket_Handshake protomessage::ProtoPacket::Handshake
Definition at line 719 of file proto-packet.pb.h.
InternalArenaConstructable_
typedef void protomessage::ProtoPacket::InternalArenaConstructable_ private
Definition at line 787 of file proto-packet.pb.h.
OnionBody
typedef ProtoPacket_OnionBody protomessage::ProtoPacket::OnionBody
Definition at line 718 of file proto-packet.pb.h.
OnionHead
typedef ProtoPacket_OnionHead protomessage::ProtoPacket::OnionHead
Definition at line 717 of file proto-packet.pb.h.
Member Enumeration Documentation
anonymous enum
anonymous enum : int
Enumerator
kHShakeFieldNumber
kOHeadFieldNumber
kOBodyFieldNumber
Definition at line 723 of file proto-packet.pb.h.
Constructor & Destructor Documentation
ProtoPacket() [1/5]
protomessage::ProtoPacket::ProtoPacket () inline
Definition at line 601 of file proto-packet.pb.h.
~ProtoPacket()
protomessage::ProtoPacket::~ProtoPacket () override
Definition at line 992 of file proto-packet.pb.cc.
References SharedDtor().
ProtoPacket() [2/5]
constexpr protomessage::ProtoPacket::ProtoPacket (::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized) explicit constexpr
Definition at line 59 of file proto-packet.pb.cc.
ProtoPacket() [3/5]
protomessage::ProtoPacket::ProtoPacket (const ProtoPacket & from)
Definition at line 963 of file proto-packet.pb.cc.
References _internal_has_h_shake(), _internal_has_o_body(), _internal_has_o_head(), h_shake_, o_body_, and o_head_.
ProtoPacket() [4/5]
protomessage::ProtoPacket::ProtoPacket (ProtoPacket && from) inline noexcept
Definition at line 606 of file proto-packet.pb.h.
ProtoPacket() [5/5]
protomessage::ProtoPacket::ProtoPacket (::PROTOBUF_NAMESPACE_ID::Arena * arena, bool is_message_owned = false) explicit protected
Definition at line 954 of file proto-packet.pb.cc.
References RegisterArenaDtor(), and SharedCtor().
Member Function Documentation
_internal_h_shake()
const ::protomessage::ProtoPacket_Handshake & protomessage::ProtoPacket::_internal_h_shake () const inline private
Definition at line 1164 of file proto-packet.pb.h.
References protomessage::_ProtoPacket_Handshake_default_instance_.
Referenced by MergeFrom().
_internal_has_h_shake()
bool protomessage::ProtoPacket::_internal_has_h_shake () const inline private
Definition at line 1152 of file proto-packet.pb.h.
References protomessage::ProtoPacket_OnionHead::_has_bits_.
Referenced by _InternalSerialize(), and ProtoPacket().
_internal_has_o_body()
bool protomessage::ProtoPacket::_internal_has_o_body () const inline private
Definition at line 1332 of file proto-packet.pb.h.
References protomessage::ProtoPacket_OnionHead::_has_bits_.
Referenced by _InternalSerialize(), and ProtoPacket().
_internal_has_o_head()
bool protomessage::ProtoPacket::_internal_has_o_head () const inline private
Definition at line 1242 of file proto-packet.pb.h.
References protomessage::ProtoPacket_OnionHead::_has_bits_.
Referenced by _InternalSerialize(), and ProtoPacket().
_internal_mutable_h_shake()
protomessage::ProtoPacket_Handshake * protomessage::ProtoPacket::_internal_mutable_h_shake () inline private
Definition at line 1208 of file proto-packet.pb.h.
References protomessage::ProtoPacket_OnionHead::_has_bits_.
Referenced by _InternalParse(), and MergeFrom().
_internal_mutable_o_body()
protomessage::ProtoPacket_OnionBody * protomessage::ProtoPacket::_internal_mutable_o_body () inline private
Definition at line 1388 of file proto-packet.pb.h.
References protomessage::ProtoPacket_OnionHead::_has_bits_.
Referenced by _InternalParse(), and MergeFrom().
_internal_mutable_o_head()
protomessage::ProtoPacket_OnionHead * protomessage::ProtoPacket::_internal_mutable_o_head () inline private
Definition at line 1298 of file proto-packet.pb.h.
References protomessage::ProtoPacket_OnionHead::_has_bits_.
Referenced by _InternalParse(), and MergeFrom().
_internal_o_body()
const ::protomessage::ProtoPacket_OnionBody & protomessage::ProtoPacket::_internal_o_body () const inline private
Definition at line 1344 of file proto-packet.pb.h.
References protomessage::_ProtoPacket_OnionBody_default_instance_.
Referenced by MergeFrom().
_internal_o_head()
const ::protomessage::ProtoPacket_OnionHead & protomessage::ProtoPacket::_internal_o_head () const inline private
Definition at line 1254 of file proto-packet.pb.h.
References protomessage::_ProtoPacket_OnionHead_default_instance_.
Referenced by MergeFrom().
_InternalParse()
const char * protomessage::ProtoPacket::_InternalParse (const char * ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext * ctx) final
Definition at line 1041 of file proto-packet.pb.cc.
References _has_bits_, _internal_mutable_h_shake(), _internal_mutable_o_body(), _internal_mutable_o_head(), and CHK_.
_InternalSerialize()
uint8_t * protomessage::ProtoPacket::_InternalSerialize (uint8_t * target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream * stream) const final
Definition at line 1096 of file proto-packet.pb.cc.
References _internal_has_h_shake(), _internal_has_o_body(), _internal_has_o_head(), protomessage::ProtoPacket::_Internal::h_shake(), protomessage::ProtoPacket::_Internal::o_body(), and protomessage::ProtoPacket::_Internal::o_head().
ArenaDtor()
void protomessage::ProtoPacket::ArenaDtor (void * object) static private
Definition at line 1006 of file proto-packet.pb.cc.
ByteSizeLong()
size_t protomessage::ProtoPacket::ByteSizeLong () const final
Definition at line 1134 of file proto-packet.pb.cc.
References _cached_size_, _has_bits_, h_shake_, o_body_, and o_head_.
Referenced by ns3::SerializationWrapper::SetData().
Clear()
void protomessage::ProtoPacket::Clear () final
Definition at line 1016 of file proto-packet.pb.cc.
References _has_bits_, protomessage::ProtoPacket_OnionHead::Clear(), protomessage::ProtoPacket_OnionBody::Clear(), protomessage::ProtoPacket_Handshake::Clear(), h_shake_, o_body_, and o_head_.
Referenced by CopyFrom().
clear_h_shake()
void protomessage::ProtoPacket::clear_h_shake () inline
Definition at line 1160 of file proto-packet.pb.h.
References protomessage::ProtoPacket_OnionHead::_has_bits_.
clear_o_body()
void protomessage::ProtoPacket::clear_o_body () inline
Definition at line 1340 of file proto-packet.pb.h.
References protomessage::ProtoPacket_OnionHead::_has_bits_.
clear_o_head()
void protomessage::ProtoPacket::clear_o_head () inline
Definition at line 1250 of file proto-packet.pb.h.
References protomessage::ProtoPacket_OnionHead::_has_bits_.
CopyFrom()
void protomessage::ProtoPacket::CopyFrom (const ProtoPacket & from)
Definition at line 1203 of file proto-packet.pb.cc.
References Clear(), and MergeFrom().
default_instance()
static const ProtoPacket& protomessage::ProtoPacket::default_instance () inline static
Definition at line 638 of file proto-packet.pb.h.
References protomessage::ProtoPacket_OnionHead::internal_default_instance().
descriptor()
static const ::PROTOBUF_NAMESPACE_ID::Descriptor* protomessage::ProtoPacket::descriptor () inline static
Definition at line 629 of file proto-packet.pb.h.
References protomessage::ProtoPacket_OnionHead::GetDescriptor().
FullMessageName()
::PROTOBUF_NAMESPACE_ID::StringPiece protomessage::ProtoPacket::FullMessageName () inline static private
Definition at line 699 of file proto-packet.pb.h.
GetCachedSize()
int protomessage::ProtoPacket::GetCachedSize () const inline final
Definition at line 689 of file proto-packet.pb.h.
References protomessage::ProtoPacket_OnionHead::_cached_size_.
GetClassData()
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData * protomessage::ProtoPacket::GetClassData () const final
Definition at line 1173 of file proto-packet.pb.cc.
References _class_data_.
GetDescriptor()
static const ::PROTOBUF_NAMESPACE_ID::Descriptor* protomessage::ProtoPacket::GetDescriptor () inline static
Definition at line 632 of file proto-packet.pb.h.
References protomessage::ProtoPacket_OnionHead::default_instance(), and protomessage::ProtoPacket_OnionHead::GetMetadata().
GetMetadata()
PROTOBUF_NAMESPACE_ID::Metadata protomessage::ProtoPacket::GetMetadata () const final
Definition at line 1226 of file proto-packet.pb.cc.
References descriptor_table_proto_2dpacket_2eproto_getter(), descriptor_table_proto_2dpacket_2eproto_once, and file_level_metadata_proto_2dpacket_2eproto.
GetReflection()
static const ::PROTOBUF_NAMESPACE_ID::Reflection* protomessage::ProtoPacket::GetReflection () inline static
Definition at line 635 of file proto-packet.pb.h.
References protomessage::ProtoPacket_OnionHead::default_instance(), and protomessage::ProtoPacket_OnionHead::GetMetadata().
h_shake()
const ::protomessage::ProtoPacket_Handshake & protomessage::ProtoPacket::h_shake () const inline
Definition at line 1169 of file proto-packet.pb.h.
has_h_shake()
bool protomessage::ProtoPacket::has_h_shake () const inline
Definition at line 1157 of file proto-packet.pb.h.
Referenced by ns3::Sink::ReceivePacket().
has_o_body()
bool protomessage::ProtoPacket::has_o_body () const inline
Definition at line 1337 of file proto-packet.pb.h.
has_o_head()
bool protomessage::ProtoPacket::has_o_head () const inline
Definition at line 1247 of file proto-packet.pb.h.
internal_default_instance()
static const ProtoPacket* protomessage::ProtoPacket::internal_default_instance () inline static
Definition at line 641 of file proto-packet.pb.h.
References protomessage::_ProtoPacket_default_instance_.
Referenced by SharedDtor().
InternalSwap()
void protomessage::ProtoPacket::InternalSwap (ProtoPacket * other) private
Definition at line 1214 of file proto-packet.pb.cc.
References _has_bits_, h_shake_, o_body_, and swap.
IsInitialized()
bool protomessage::ProtoPacket::IsInitialized () const final
Definition at line 1210 of file proto-packet.pb.cc.
MergeFrom()
void protomessage::ProtoPacket::MergeFrom (const ProtoPacket & from)
Definition at line 1182 of file proto-packet.pb.cc.
References _has_bits_, _internal_h_shake(), _internal_mutable_h_shake(), _internal_mutable_o_body(), _internal_mutable_o_head(), _internal_o_body(), _internal_o_head(), and protomessage::ProtoPacket_OnionBody::MergeFrom().
Referenced by CopyFrom(), and MergeImpl().
MergeImpl()
void protomessage::ProtoPacket::MergeImpl (::PROTOBUF_NAMESPACE_ID::Message * to, const ::PROTOBUF_NAMESPACE_ID::Message & from) static private
Definition at line 1175 of file proto-packet.pb.cc.
References MergeFrom().
mutable_h_shake()
protomessage::ProtoPacket_Handshake * protomessage::ProtoPacket::mutable_h_shake () inline
Definition at line 1216 of file proto-packet.pb.h.
Referenced by ns3::SensorNode::Handshake(), and ns3::Sink::ReceivePacket().
mutable_o_body()
protomessage::ProtoPacket_OnionBody * protomessage::ProtoPacket::mutable_o_body () inline
Definition at line 1396 of file proto-packet.pb.h.
Referenced by ns3::SensorNode::ReceivePacket(), ns3::Sink::ReceivePacket(), and ns3::Sink::SendOnion().
mutable_o_head()
protomessage::ProtoPacket_OnionHead * protomessage::ProtoPacket::mutable_o_head () inline
Definition at line 1306 of file proto-packet.pb.h.
Referenced by ns3::SensorNode::ReceivePacket(), ns3::Sink::ReceivePacket(), and ns3::Sink::SendOnion().
New()
ProtoPacket* protomessage::ProtoPacket::New (::PROTOBUF_NAMESPACE_ID::Arena * arena = nullptr) const inline final
Definition at line 672 of file proto-packet.pb.h.
o_body()
const ::protomessage::ProtoPacket_OnionBody & protomessage::ProtoPacket::o_body () const inline
Definition at line 1349 of file proto-packet.pb.h.
o_head()
const ::protomessage::ProtoPacket_OnionHead & protomessage::ProtoPacket::o_head () const inline
Definition at line 1259 of file proto-packet.pb.h.
operator=() [1/2]
ProtoPacket& protomessage::ProtoPacket::operator= (const ProtoPacket & from) inline
Definition at line 611 of file proto-packet.pb.h.
References protomessage::ProtoPacket_OnionHead::CopyFrom().
operator=() [2/2]
ProtoPacket& protomessage::ProtoPacket::operator= (ProtoPacket && from) inline noexcept
Definition at line 615 of file proto-packet.pb.h.
References protomessage::ProtoPacket_OnionHead::CopyFrom(), and protomessage::ProtoPacket_OnionHead::InternalSwap().
RegisterArenaDtor()
void protomessage::ProtoPacket::RegisterArenaDtor (::PROTOBUF_NAMESPACE_ID::Arena * arena) inline private
Definition at line 1010 of file proto-packet.pb.cc.
Referenced by ProtoPacket().
release_h_shake()
protomessage::ProtoPacket_Handshake * protomessage::ProtoPacket::release_h_shake () inline
Definition at line 1186 of file proto-packet.pb.h.
References protomessage::ProtoPacket_OnionHead::_has_bits_.
release_o_body()
protomessage::ProtoPacket_OnionBody * protomessage::ProtoPacket::release_o_body () inline
Definition at line 1366 of file proto-packet.pb.h.
References protomessage::ProtoPacket_OnionHead::_has_bits_.
release_o_head()
protomessage::ProtoPacket_OnionHead * protomessage::ProtoPacket::release_o_head () inline
Definition at line 1276 of file proto-packet.pb.h.
References protomessage::ProtoPacket_OnionHead::_has_bits_.
set_allocated_h_shake()
void protomessage::ProtoPacket::set_allocated_h_shake (::protomessage::ProtoPacket_Handshake * h_shake) inline
Definition at line 1221 of file proto-packet.pb.h.
References protomessage::ProtoPacket_OnionHead::_has_bits_.
set_allocated_o_body()
void protomessage::ProtoPacket::set_allocated_o_body (::protomessage::ProtoPacket_OnionBody * o_body) inline
Definition at line 1401 of file proto-packet.pb.h.
References protomessage::ProtoPacket_OnionHead::_has_bits_.
set_allocated_o_head()
void protomessage::ProtoPacket::set_allocated_o_head (::protomessage::ProtoPacket_OnionHead * o_head) inline
Definition at line 1311 of file proto-packet.pb.h.
References protomessage::ProtoPacket_OnionHead::_has_bits_.
SetCachedSize()
void protomessage::ProtoPacket::SetCachedSize (int size) const final private
Definition at line 1012 of file proto-packet.pb.cc.
References _cached_size_.
SharedCtor()
void protomessage::ProtoPacket::SharedCtor () inline private
Definition at line 985 of file proto-packet.pb.cc.
References h_shake_, and o_body_.
Referenced by ProtoPacket().
SharedDtor()
void protomessage::ProtoPacket::SharedDtor () inline private
Definition at line 999 of file proto-packet.pb.cc.
References h_shake_, internal_default_instance(), o_body_, and o_head_.
Referenced by ~ProtoPacket().
Swap()
void protomessage::ProtoPacket::Swap (ProtoPacket * other) inline
Definition at line 651 of file proto-packet.pb.h.
References protomessage::ProtoPacket_OnionHead::InternalSwap().
unsafe_arena_release_h_shake()
protomessage::ProtoPacket_Handshake * protomessage::ProtoPacket::unsafe_arena_release_h_shake () inline
Definition at line 1201 of file proto-packet.pb.h.
References protomessage::ProtoPacket_OnionHead::_has_bits_.
unsafe_arena_release_o_body()
protomessage::ProtoPacket_OnionBody * protomessage::ProtoPacket::unsafe_arena_release_o_body () inline
Definition at line 1381 of file proto-packet.pb.h.
References protomessage::ProtoPacket_OnionHead::_has_bits_.
unsafe_arena_release_o_head()
protomessage::ProtoPacket_OnionHead * protomessage::ProtoPacket::unsafe_arena_release_o_head () inline
Definition at line 1291 of file proto-packet.pb.h.
References protomessage::ProtoPacket_OnionHead::_has_bits_.
unsafe_arena_set_allocated_h_shake()
void protomessage::ProtoPacket::unsafe_arena_set_allocated_h_shake (::protomessage::ProtoPacket_Handshake * h_shake) inline
Definition at line 1173 of file proto-packet.pb.h.
References protomessage::ProtoPacket_OnionHead::_has_bits_.
unsafe_arena_set_allocated_o_body()
void protomessage::ProtoPacket::unsafe_arena_set_allocated_o_body (::protomessage::ProtoPacket_OnionBody * o_body) inline
Definition at line 1353 of file proto-packet.pb.h.
References protomessage::ProtoPacket_OnionHead::_has_bits_.
unsafe_arena_set_allocated_o_head()
void protomessage::ProtoPacket::unsafe_arena_set_allocated_o_head (::protomessage::ProtoPacket_OnionHead * o_head) inline
Definition at line 1263 of file proto-packet.pb.h.
References protomessage::ProtoPacket_OnionHead::_has_bits_.
UnsafeArenaSwap()
void protomessage::ProtoPacket::UnsafeArenaSwap (ProtoPacket * other) inline
Definition at line 664 of file proto-packet.pb.h.
References protomessage::ProtoPacket_OnionHead::InternalSwap().
Friends And Related Function Documentation
::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper
template<typename T > friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper friend
Definition at line 784 of file proto-packet.pb.h.
::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata
friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata friend
Definition at line 698 of file proto-packet.pb.h.
::TableStruct_proto_2dpacket_2eproto
friend struct ::TableStruct_proto_2dpacket_2eproto friend
Definition at line 794 of file proto-packet.pb.h.
swap
void swap (ProtoPacket & a, ProtoPacket & b) friend
Definition at line 648 of file proto-packet.pb.h.
Referenced by InternalSwap().
Member Data Documentation
_cached_size_
mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize protomessage::ProtoPacket::_cached_size_ private
Definition at line 790 of file proto-packet.pb.h.
Referenced by ByteSizeLong(), and SetCachedSize().
_class_data_
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData protomessage::ProtoPacket::_class_data_ static
Initial value:
= {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    ProtoPacket::MergeImpl
}
Definition at line 710 of file proto-packet.pb.h.
Referenced by GetClassData().
_has_bits_
::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> protomessage::ProtoPacket::_has_bits_ private
Definition at line 789 of file proto-packet.pb.h.
Referenced by _InternalParse(), ByteSizeLong(), Clear(), InternalSwap(), and MergeFrom().
h_shake_
::protomessage::ProtoPacket_Handshake* protomessage::ProtoPacket::h_shake_ private
Definition at line 791 of file proto-packet.pb.h.
Referenced by ByteSizeLong(), Clear(), protomessage::ProtoPacket::_Internal::h_shake(), InternalSwap(), ProtoPacket(), SharedCtor(), and SharedDtor().
kIndexInFileMessages
constexpr int protomessage::ProtoPacket::kIndexInFileMessages static constexpr
Initial value:
=
    3
Definition at line 645 of file proto-packet.pb.h.
o_body_
::protomessage::ProtoPacket_OnionBody* protomessage::ProtoPacket::o_body_ private
Definition at line 793 of file proto-packet.pb.h.
Referenced by ByteSizeLong(), Clear(), InternalSwap(), protomessage::ProtoPacket::_Internal::o_body(), ProtoPacket(), SharedCtor(), and SharedDtor().
o_head_
::protomessage::ProtoPacket_OnionHead* protomessage::ProtoPacket::o_head_ private
Definition at line 792 of file proto-packet.pb.h.
Referenced by ByteSizeLong(), Clear(), protomessage::ProtoPacket::_Internal::o_head(), ProtoPacket(), and SharedDtor().
The documentation for this class was generated from the following files:
src/onion_routing_wsn/protobuf/proto-packet.pb.h
src/onion_routing_wsn/protobuf/proto-packet.pb.cc