ns-3: protomessage::ProtoPacket_Handshake Class Reference
protomessage::ProtoPacket_Handshake Class Reference final
#include "proto-packet.pb.h"
Classes
class _Internal
Public Types
enum : int { kPublickeyFieldNumber = 1 }
Public Member Functions
ProtoPacket_Handshake ()
constexpr ProtoPacket_Handshake (::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
ProtoPacket_Handshake (const ProtoPacket_Handshake &from)
ProtoPacket_Handshake (ProtoPacket_Handshake &&from) noexcept
~ProtoPacket_Handshake () override
const char * _InternalParse (const char *ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext *ctx) final
uint8_t * _InternalSerialize (uint8_t *target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream *stream) const final
size_t ByteSizeLong () const final
PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear () final
void clear_publickey ()
void CopyFrom (const ProtoPacket_Handshake &from)
int GetCachedSize () const final
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData * GetClassData () const final
::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata () const final
bool has_publickey () const
bool IsInitialized () const final
void MergeFrom (const ProtoPacket_Handshake &from)
std::string * mutable_publickey ()
ProtoPacket_Handshake * New (::PROTOBUF_NAMESPACE_ID::Arena *arena=nullptr) const final
ProtoPacket_Handshake & operator= (const ProtoPacket_Handshake &from)
ProtoPacket_Handshake & operator= (ProtoPacket_Handshake &&from) noexcept
const std::string & publickey () const
PROTOBUF_NODISCARD std::string * release_publickey ()
void set_allocated_publickey (std::string *publickey)
template<typename ArgT0 = const std::string&, typename... ArgT>
void set_publickey (ArgT0 &&arg0, ArgT... args)
template<typename ArgT0 , typename... ArgT>
PROTOBUF_ALWAYS_INLINE void set_publickey (ArgT0 &&arg0, ArgT... args)
void Swap (ProtoPacket_Handshake *other)
void UnsafeArenaSwap (ProtoPacket_Handshake *other)
Static Public Member Functions
static const ProtoPacket_Handshake & default_instance ()
static const ::PROTOBUF_NAMESPACE_ID::Descriptor * descriptor ()
static const ::PROTOBUF_NAMESPACE_ID::Descriptor * GetDescriptor ()
static const ::PROTOBUF_NAMESPACE_ID::Reflection * GetReflection ()
static const ProtoPacket_Handshake * internal_default_instance ()
Static Public Attributes
static const ClassData _class_data_
static constexpr int kIndexInFileMessages
Protected Member Functions
ProtoPacket_Handshake (::PROTOBUF_NAMESPACE_ID::Arena *arena, bool is_message_owned=false)
Private Types
typedef void DestructorSkippable_
typedef void InternalArenaConstructable_
Private Member Functions
bool _internal_has_publickey () const
std::string * _internal_mutable_publickey ()
const std::string & _internal_publickey () const
PROTOBUF_ALWAYS_INLINE void _internal_set_publickey (const std::string &value)
void InternalSwap (ProtoPacket_Handshake *other)
void RegisterArenaDtor (::PROTOBUF_NAMESPACE_ID::Arena *arena)
void SetCachedSize (int size) const final
void SharedCtor ()
void SharedDtor ()
Static Private Member Functions
static void ArenaDtor (void *object)
::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName ()
static void MergeImpl (::PROTOBUF_NAMESPACE_ID::Message *to, const ::PROTOBUF_NAMESPACE_ID::Message &from)
Private Attributes
mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_
::PROTOBUF_NAMESPACE_ID::internal::HasBits< 1 > _has_bits_
::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr publickey_
Friends
template<typename T >
class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper
class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata
struct ::TableStruct_proto_2dpacket_2eproto
void swap (ProtoPacket_Handshake &a, ProtoPacket_Handshake &b)
Detailed Description
Definition at line 442 of file proto-packet.pb.h.
Member Typedef Documentation
DestructorSkippable_
typedef void protomessage::ProtoPacket_Handshake::DestructorSkippable_ private
Definition at line 590 of file proto-packet.pb.h.
InternalArenaConstructable_
typedef void protomessage::ProtoPacket_Handshake::InternalArenaConstructable_ private
Definition at line 589 of file proto-packet.pb.h.
Member Enumeration Documentation
anonymous enum
anonymous enum : int
Enumerator
kPublickeyFieldNumber
Definition at line 563 of file proto-packet.pb.h.
Constructor & Destructor Documentation
ProtoPacket_Handshake() [1/5]
protomessage::ProtoPacket_Handshake::ProtoPacket_Handshake () inline
Definition at line 445 of file proto-packet.pb.h.
~ProtoPacket_Handshake()
protomessage::ProtoPacket_Handshake::~ProtoPacket_Handshake () override
Definition at line 753 of file proto-packet.pb.cc.
References SharedDtor().
ProtoPacket_Handshake() [2/5]
constexpr protomessage::ProtoPacket_Handshake::ProtoPacket_Handshake (::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized) explicit constexpr
Definition at line 47 of file proto-packet.pb.cc.
ProtoPacket_Handshake() [3/5]
protomessage::ProtoPacket_Handshake::ProtoPacket_Handshake (const ProtoPacket_Handshake & from)
Definition at line 731 of file proto-packet.pb.cc.
References _internal_has_publickey(), _internal_publickey(), and publickey_.
ProtoPacket_Handshake() [4/5]
protomessage::ProtoPacket_Handshake::ProtoPacket_Handshake (ProtoPacket_Handshake && from) inline noexcept
Definition at line 450 of file proto-packet.pb.h.
ProtoPacket_Handshake() [5/5]
protomessage::ProtoPacket_Handshake::ProtoPacket_Handshake (::PROTOBUF_NAMESPACE_ID::Arena * arena, bool is_message_owned = false) explicit protected
Definition at line 722 of file proto-packet.pb.cc.
References RegisterArenaDtor(), and SharedCtor().
Member Function Documentation
_internal_has_publickey()
bool protomessage::ProtoPacket_Handshake::_internal_has_publickey () const inline private
Definition at line 1079 of file proto-packet.pb.h.
References protomessage::ProtoPacket_OnionHead::_has_bits_.
Referenced by _InternalSerialize(), MergeFrom(), and ProtoPacket_Handshake().
_internal_mutable_publickey()
std::string * protomessage::ProtoPacket_Handshake::_internal_mutable_publickey () inline private
Definition at line 1113 of file proto-packet.pb.h.
References protomessage::ProtoPacket_OnionHead::_has_bits_.
Referenced by _InternalParse().
_internal_publickey()
const std::string & protomessage::ProtoPacket_Handshake::_internal_publickey () const inline private
Definition at line 1106 of file proto-packet.pb.h.
Referenced by _InternalSerialize(), ByteSizeLong(), MergeFrom(), and ProtoPacket_Handshake().
_internal_set_publickey()
void protomessage::ProtoPacket_Handshake::_internal_set_publickey (const std::string & value) inline private
Definition at line 1109 of file proto-packet.pb.h.
References protomessage::ProtoPacket_OnionHead::_has_bits_.
Referenced by MergeFrom().
_InternalParse()
const char * protomessage::ProtoPacket_Handshake::_InternalParse (const char * ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext * ctx) final
Definition at line 789 of file proto-packet.pb.cc.
References _has_bits_, _internal_mutable_publickey(), and CHK_.
_InternalSerialize()
uint8_t * protomessage::ProtoPacket_Handshake::_InternalSerialize (uint8_t * target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream * stream) const final
Definition at line 829 of file proto-packet.pb.cc.
References _internal_has_publickey(), and _internal_publickey().
ArenaDtor()
void protomessage::ProtoPacket_Handshake::ArenaDtor (void * object) static private
Definition at line 765 of file proto-packet.pb.cc.
ByteSizeLong()
size_t protomessage::ProtoPacket_Handshake::ByteSizeLong () const final
Definition at line 849 of file proto-packet.pb.cc.
References _cached_size_, _has_bits_, and _internal_publickey().
Clear()
void protomessage::ProtoPacket_Handshake::Clear () final
Definition at line 775 of file proto-packet.pb.cc.
References _has_bits_, and publickey_.
Referenced by protomessage::ProtoPacket::Clear(), and CopyFrom().
clear_publickey()
void protomessage::ProtoPacket_Handshake::clear_publickey () inline
Definition at line 1086 of file proto-packet.pb.h.
References protomessage::ProtoPacket_OnionHead::_has_bits_.
CopyFrom()
void protomessage::ProtoPacket_Handshake::CopyFrom (const ProtoPacket_Handshake & from)
Definition at line 893 of file proto-packet.pb.cc.
References Clear(), and MergeFrom().
default_instance()
static const ProtoPacket_Handshake& protomessage::ProtoPacket_Handshake::default_instance () inline static
Definition at line 482 of file proto-packet.pb.h.
References protomessage::ProtoPacket_OnionHead::internal_default_instance().
descriptor()
static const ::PROTOBUF_NAMESPACE_ID::Descriptor* protomessage::ProtoPacket_Handshake::descriptor () inline static
Definition at line 473 of file proto-packet.pb.h.
References protomessage::ProtoPacket_OnionHead::GetDescriptor().
FullMessageName()
::PROTOBUF_NAMESPACE_ID::StringPiece protomessage::ProtoPacket_Handshake::FullMessageName () inline static private
Definition at line 543 of file proto-packet.pb.h.
GetCachedSize()
int protomessage::ProtoPacket_Handshake::GetCachedSize () const inline final
Definition at line 533 of file proto-packet.pb.h.
References protomessage::ProtoPacket_OnionHead::_cached_size_.
GetClassData()
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData * protomessage::ProtoPacket_Handshake::GetClassData () const final
Definition at line 872 of file proto-packet.pb.cc.
References _class_data_.
GetDescriptor()
static const ::PROTOBUF_NAMESPACE_ID::Descriptor* protomessage::ProtoPacket_Handshake::GetDescriptor () inline static
Definition at line 476 of file proto-packet.pb.h.
References protomessage::ProtoPacket_OnionHead::default_instance(), and protomessage::ProtoPacket_OnionHead::GetMetadata().
GetMetadata()
PROTOBUF_NAMESPACE_ID::Metadata protomessage::ProtoPacket_Handshake::GetMetadata () const final
Definition at line 917 of file proto-packet.pb.cc.
References descriptor_table_proto_2dpacket_2eproto_getter(), descriptor_table_proto_2dpacket_2eproto_once, and file_level_metadata_proto_2dpacket_2eproto.
GetReflection()
static const ::PROTOBUF_NAMESPACE_ID::Reflection* protomessage::ProtoPacket_Handshake::GetReflection () inline static
Definition at line 479 of file proto-packet.pb.h.
References protomessage::ProtoPacket_OnionHead::default_instance(), and protomessage::ProtoPacket_OnionHead::GetMetadata().
has_publickey()
bool protomessage::ProtoPacket_Handshake::has_publickey () const inline
Definition at line 1083 of file proto-packet.pb.h.
internal_default_instance()
static const ProtoPacket_Handshake* protomessage::ProtoPacket_Handshake::internal_default_instance () inline static
Definition at line 485 of file proto-packet.pb.h.
References protomessage::_ProtoPacket_Handshake_default_instance_.
InternalSwap()
void protomessage::ProtoPacket_Handshake::InternalSwap (ProtoPacket_Handshake * other) private
Definition at line 904 of file proto-packet.pb.cc.
References _has_bits_, InternalSwap(), publickey_, and swap.
Referenced by InternalSwap().
IsInitialized()
bool protomessage::ProtoPacket_Handshake::IsInitialized () const final
Definition at line 900 of file proto-packet.pb.cc.
MergeFrom()
void protomessage::ProtoPacket_Handshake::MergeFrom (const ProtoPacket_Handshake & from)
Definition at line 881 of file proto-packet.pb.cc.
References _internal_has_publickey(), _internal_publickey(), and _internal_set_publickey().
Referenced by CopyFrom(), and MergeImpl().
MergeImpl()
void protomessage::ProtoPacket_Handshake::MergeImpl (::PROTOBUF_NAMESPACE_ID::Message * to, const ::PROTOBUF_NAMESPACE_ID::Message & from) static private
Definition at line 874 of file proto-packet.pb.cc.
References MergeFrom().
mutable_publickey()
std::string * protomessage::ProtoPacket_Handshake::mutable_publickey () inline
Definition at line 1101 of file proto-packet.pb.h.
New()
ProtoPacket_Handshake* protomessage::ProtoPacket_Handshake::New (::PROTOBUF_NAMESPACE_ID::Arena * arena = nullptr) const inline final
Definition at line 516 of file proto-packet.pb.h.
operator=() [1/2]
ProtoPacket_Handshake& protomessage::ProtoPacket_Handshake::operator= (const ProtoPacket_Handshake & from) inline
Definition at line 455 of file proto-packet.pb.h.
References protomessage::ProtoPacket_OnionHead::CopyFrom().
operator=() [2/2]
ProtoPacket_Handshake& protomessage::ProtoPacket_Handshake::operator= (ProtoPacket_Handshake && from) inline noexcept
Definition at line 459 of file proto-packet.pb.h.
References protomessage::ProtoPacket_OnionHead::CopyFrom(), and protomessage::ProtoPacket_OnionHead::InternalSwap().
publickey()
const std::string & protomessage::ProtoPacket_Handshake::publickey () const inline
Definition at line 1090 of file proto-packet.pb.h.
Referenced by ns3::Sink::RecvHandshake().
RegisterArenaDtor()
void protomessage::ProtoPacket_Handshake::RegisterArenaDtor (::PROTOBUF_NAMESPACE_ID::Arena * arena) inline private
Definition at line 769 of file proto-packet.pb.cc.
Referenced by ProtoPacket_Handshake().
release_publickey()
std::string * protomessage::ProtoPacket_Handshake::release_publickey () inline
Definition at line 1117 of file proto-packet.pb.h.
References protomessage::ProtoPacket_OnionHead::_has_bits_.
set_allocated_publickey()
void protomessage::ProtoPacket_Handshake::set_allocated_publickey (std::string * publickey) inline
Definition at line 1131 of file proto-packet.pb.h.
References protomessage::ProtoPacket_OnionHead::_has_bits_.
set_publickey() [1/2]
template<typename ArgT0 = const std::string&, typename... ArgT> void protomessage::ProtoPacket_Handshake::set_publickey (ArgT0 && arg0, ArgT... args)
Referenced by ns3::SensorNode::Handshake().
set_publickey() [2/2]
template<typename ArgT0 , typename... ArgT> PROTOBUF_ALWAYS_INLINE void protomessage::ProtoPacket_Handshake::set_publickey (ArgT0 && arg0, ArgT... args) inline
Definition at line 1096 of file proto-packet.pb.h.
References protomessage::ProtoPacket_OnionHead::_has_bits_.
SetCachedSize()
void protomessage::ProtoPacket_Handshake::SetCachedSize (int size) const final private
Definition at line 771 of file proto-packet.pb.cc.
References _cached_size_.
SharedCtor()
void protomessage::ProtoPacket_Handshake::SharedCtor () inline private
Definition at line 746 of file proto-packet.pb.cc.
References publickey_.
Referenced by ProtoPacket_Handshake().
SharedDtor()
void protomessage::ProtoPacket_Handshake::SharedDtor () inline private
Definition at line 760 of file proto-packet.pb.cc.
References publickey_.
Referenced by ~ProtoPacket_Handshake().
Swap()
void protomessage::ProtoPacket_Handshake::Swap (ProtoPacket_Handshake * other) inline
Definition at line 495 of file proto-packet.pb.h.
References protomessage::ProtoPacket_OnionHead::InternalSwap().
UnsafeArenaSwap()
void protomessage::ProtoPacket_Handshake::UnsafeArenaSwap (ProtoPacket_Handshake * other) inline
Definition at line 508 of file proto-packet.pb.h.
References protomessage::ProtoPacket_OnionHead::InternalSwap().
Friends And Related Function Documentation
::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper
template<typename T > friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper friend
Definition at line 586 of file proto-packet.pb.h.
::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata
friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata friend
Definition at line 542 of file proto-packet.pb.h.
::TableStruct_proto_2dpacket_2eproto
friend struct ::TableStruct_proto_2dpacket_2eproto friend
Definition at line 594 of file proto-packet.pb.h.
swap
void swap (ProtoPacket_Handshake & a, ProtoPacket_Handshake & b) friend
Definition at line 492 of file proto-packet.pb.h.
Referenced by InternalSwap().
Member Data Documentation
_cached_size_
mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize protomessage::ProtoPacket_Handshake::_cached_size_ private
Definition at line 592 of file proto-packet.pb.h.
Referenced by ByteSizeLong(), and SetCachedSize().
_class_data_
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData protomessage::ProtoPacket_Handshake::_class_data_ static
Initial value:
= {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    ProtoPacket_Handshake::MergeImpl
}
Definition at line 554 of file proto-packet.pb.h.
Referenced by GetClassData().
_has_bits_
::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> protomessage::ProtoPacket_Handshake::_has_bits_ private
Definition at line 591 of file proto-packet.pb.h.
Referenced by _InternalParse(), ByteSizeLong(), Clear(), and InternalSwap().
kIndexInFileMessages
constexpr int protomessage::ProtoPacket_Handshake::kIndexInFileMessages static constexpr
Initial value:
=
    2
Definition at line 489 of file proto-packet.pb.h.
publickey_
::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr protomessage::ProtoPacket_Handshake::publickey_ private
Definition at line 593 of file proto-packet.pb.h.
Referenced by Clear(), InternalSwap(), ProtoPacket_Handshake(), SharedCtor(), and SharedDtor().
The documentation for this class was generated from the following files:
src/onion_routing_wsn/protobuf/proto-packet.pb.h
src/onion_routing_wsn/protobuf/proto-packet.pb.cc