ns-3: protomessage::ProtoPacket::_Internal Class Reference
protomessage::ProtoPacket::_Internal Class Reference
Public Types
using HasBits = decltype(std::declval< ProtoPacket >()._has_bits_)
Static Public Member Functions
static const ::protomessage::ProtoPacket_Handshake & h_shake (const ProtoPacket *msg)
static const ::protomessage::ProtoPacket_OnionBody & o_body (const ProtoPacket *msg)
static const ::protomessage::ProtoPacket_OnionHead & o_head (const ProtoPacket *msg)
static void set_has_h_shake (HasBits *has_bits)
static void set_has_o_body (HasBits *has_bits)
static void set_has_o_head (HasBits *has_bits)
Detailed Description
Definition at line 925 of file proto-packet.pb.cc.
Member Typedef Documentation
HasBits
using protomessage::ProtoPacket::_Internal::HasBits = decltype(std::declval<ProtoPacket>()._has_bits_)
Definition at line 927 of file proto-packet.pb.cc.
Member Function Documentation
h_shake()
const ::protomessage::ProtoPacket_Handshake & protomessage::ProtoPacket::_Internal::h_shake (const ProtoPacket * msg) static
Definition at line 943 of file proto-packet.pb.cc.
References protomessage::ProtoPacket::h_shake_.
Referenced by protomessage::ProtoPacket::_InternalSerialize().
o_body()
const ::protomessage::ProtoPacket_OnionBody & protomessage::ProtoPacket::_Internal::o_body (const ProtoPacket * msg) static
Definition at line 951 of file proto-packet.pb.cc.
References protomessage::ProtoPacket::o_body_.
Referenced by protomessage::ProtoPacket::_InternalSerialize().
o_head()
const ::protomessage::ProtoPacket_OnionHead & protomessage::ProtoPacket::_Internal::o_head (const ProtoPacket * msg) static
Definition at line 947 of file proto-packet.pb.cc.
References protomessage::ProtoPacket::o_head_.
Referenced by protomessage::ProtoPacket::_InternalSerialize().
set_has_h_shake()
static void protomessage::ProtoPacket::_Internal::set_has_h_shake (HasBits * has_bits) inline static
Definition at line 929 of file proto-packet.pb.cc.
set_has_o_body()
static void protomessage::ProtoPacket::_Internal::set_has_o_body (HasBits * has_bits) inline static
Definition at line 937 of file proto-packet.pb.cc.
set_has_o_head()
static void protomessage::ProtoPacket::_Internal::set_has_o_head (HasBits * has_bits) inline static
Definition at line 933 of file proto-packet.pb.cc.
The documentation for this class was generated from the following file:
src/onion_routing_wsn/protobuf/proto-packet.pb.cc