ns-3: protomessage::ProtoPacket_OnionHead Class Reference
protomessage::ProtoPacket_OnionHead Class Reference final
#include "proto-packet.pb.h"
Classes
class _Internal
Public Types
enum : int { kOnionMessageFieldNumber = 2, kPaddingFieldNumber = 3, kOnionIdFieldNumber = 1 }
Public Member Functions
ProtoPacket_OnionHead ()
constexpr ProtoPacket_OnionHead (::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
ProtoPacket_OnionHead (const ProtoPacket_OnionHead &from)
ProtoPacket_OnionHead (ProtoPacket_OnionHead &&from) noexcept
~ProtoPacket_OnionHead () override
const char * _InternalParse (const char *ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext *ctx) final
uint8_t * _InternalSerialize (uint8_t *target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream *stream) const final
size_t ByteSizeLong () const final
PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear () final
void clear_onion_message ()
void clear_onionid ()
void clear_padding ()
void CopyFrom (const ProtoPacket_OnionHead &from)
int GetCachedSize () const final
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData * GetClassData () const final
::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata () const final
bool has_onion_message () const
bool has_onionid () const
bool has_padding () const
bool IsInitialized () const final
void MergeFrom (const ProtoPacket_OnionHead &from)
std::string * mutable_onion_message ()
std::string * mutable_padding ()
ProtoPacket_OnionHead * New (::PROTOBUF_NAMESPACE_ID::Arena *arena=nullptr) const final
const std::string & onion_message () const
int32_t onionid () const
ProtoPacket_OnionHead & operator= (const ProtoPacket_OnionHead &from)
ProtoPacket_OnionHead & operator= (ProtoPacket_OnionHead &&from) noexcept
const std::string & padding () const
PROTOBUF_NODISCARD std::string * release_onion_message ()
PROTOBUF_NODISCARD std::string * release_padding ()
void set_allocated_onion_message (std::string *onion_message)
void set_allocated_padding (std::string *padding)
template<typename ArgT0 = const std::string&, typename... ArgT>
void set_onion_message (ArgT0 &&arg0, ArgT... args)
template<typename ArgT0 , typename... ArgT>
PROTOBUF_ALWAYS_INLINE void set_onion_message (ArgT0 &&arg0, ArgT... args)
void set_onionid (int32_t value)
template<typename ArgT0 = const std::string&, typename... ArgT>
void set_padding (ArgT0 &&arg0, ArgT... args)
template<typename ArgT0 , typename... ArgT>
PROTOBUF_ALWAYS_INLINE void set_padding (ArgT0 &&arg0, ArgT... args)
void Swap (ProtoPacket_OnionHead *other)
void UnsafeArenaSwap (ProtoPacket_OnionHead *other)
Static Public Member Functions
static const ProtoPacket_OnionHead & default_instance ()
static const ::PROTOBUF_NAMESPACE_ID::Descriptor * descriptor ()
static const ::PROTOBUF_NAMESPACE_ID::Descriptor * GetDescriptor ()
static const ::PROTOBUF_NAMESPACE_ID::Reflection * GetReflection ()
static const ProtoPacket_OnionHead * internal_default_instance ()
Static Public Attributes
static const ClassData _class_data_
static constexpr int kIndexInFileMessages
Protected Member Functions
ProtoPacket_OnionHead (::PROTOBUF_NAMESPACE_ID::Arena *arena, bool is_message_owned=false)
Private Types
typedef void DestructorSkippable_
typedef void InternalArenaConstructable_
Private Member Functions
bool _internal_has_onion_message () const
bool _internal_has_onionid () const
bool _internal_has_padding () const
std::string * _internal_mutable_onion_message ()
std::string * _internal_mutable_padding ()
const std::string & _internal_onion_message () const
int32_t _internal_onionid () const
const std::string & _internal_padding () const
PROTOBUF_ALWAYS_INLINE void _internal_set_onion_message (const std::string &value)
void _internal_set_onionid (int32_t value)
PROTOBUF_ALWAYS_INLINE void _internal_set_padding (const std::string &value)
void InternalSwap (ProtoPacket_OnionHead *other)
void RegisterArenaDtor (::PROTOBUF_NAMESPACE_ID::Arena *arena)
void SetCachedSize (int size) const final
void SharedCtor ()
void SharedDtor ()
Static Private Member Functions
static void ArenaDtor (void *object)
::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName ()
static void MergeImpl (::PROTOBUF_NAMESPACE_ID::Message *to, const ::PROTOBUF_NAMESPACE_ID::Message &from)
Private Attributes
mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_
::PROTOBUF_NAMESPACE_ID::internal::HasBits< 1 > _has_bits_
::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr onion_message_
int32_t onionid_
::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr padding_
Friends
template<typename T >
class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper
class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata
struct ::TableStruct_proto_2dpacket_2eproto
void swap (ProtoPacket_OnionHead &a, ProtoPacket_OnionHead &b)
Detailed Description
Definition at line 80 of file proto-packet.pb.h.
Member Typedef Documentation
DestructorSkippable_
typedef void protomessage::ProtoPacket_OnionHead::DestructorSkippable_ private
Definition at line 261 of file proto-packet.pb.h.
InternalArenaConstructable_
typedef void protomessage::ProtoPacket_OnionHead::InternalArenaConstructable_ private
Definition at line 260 of file proto-packet.pb.h.
Member Enumeration Documentation
anonymous enum
anonymous enum : int
Enumerator
kOnionMessageFieldNumber
kPaddingFieldNumber
kOnionIdFieldNumber
Definition at line 201 of file proto-packet.pb.h.
Constructor & Destructor Documentation
ProtoPacket_OnionHead() [1/5]
protomessage::ProtoPacket_OnionHead::ProtoPacket_OnionHead () inline
Definition at line 83 of file proto-packet.pb.h.
~ProtoPacket_OnionHead()
protomessage::ProtoPacket_OnionHead::~ProtoPacket_OnionHead () override
Definition at line 228 of file proto-packet.pb.cc.
References SharedDtor().
ProtoPacket_OnionHead() [2/5]
constexpr protomessage::ProtoPacket_OnionHead::ProtoPacket_OnionHead (::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized) explicit constexpr
Definition at line 20 of file proto-packet.pb.cc.
ProtoPacket_OnionHead() [3/5]
protomessage::ProtoPacket_OnionHead::ProtoPacket_OnionHead (const ProtoPacket_OnionHead & from)
Definition at line 192 of file proto-packet.pb.cc.
References _internal_has_onion_message(), _internal_has_padding(), _internal_onion_message(), _internal_padding(), onion_message_, onionid_, and padding_.
ProtoPacket_OnionHead() [4/5]
protomessage::ProtoPacket_OnionHead::ProtoPacket_OnionHead (ProtoPacket_OnionHead && from) inline noexcept
Definition at line 88 of file proto-packet.pb.h.
ProtoPacket_OnionHead() [5/5]
protomessage::ProtoPacket_OnionHead::ProtoPacket_OnionHead (::PROTOBUF_NAMESPACE_ID::Arena * arena, bool is_message_owned = false) explicit protected
Definition at line 183 of file proto-packet.pb.cc.
References RegisterArenaDtor(), and SharedCtor().
Member Function Documentation
_internal_has_onion_message()
bool protomessage::ProtoPacket_OnionHead::_internal_has_onion_message () const inline private
Definition at line 836 of file proto-packet.pb.h.
References _has_bits_.
Referenced by _InternalSerialize(), has_onion_message(), ProtoPacket_OnionHead(), and release_onion_message().
_internal_has_onionid()
bool protomessage::ProtoPacket_OnionHead::_internal_has_onionid () const inline private
Definition at line 808 of file proto-packet.pb.h.
References _has_bits_.
Referenced by _InternalSerialize(), and has_onionid().
_internal_has_padding()
bool protomessage::ProtoPacket_OnionHead::_internal_has_padding () const inline private
Definition at line 905 of file proto-packet.pb.h.
References _has_bits_.
Referenced by _InternalSerialize(), has_padding(), protomessage::ProtoPacket_OnionBody::has_padding(), ProtoPacket_OnionHead(), release_padding(), and protomessage::ProtoPacket_OnionBody::release_padding().
_internal_mutable_onion_message()
std::string * protomessage::ProtoPacket_OnionHead::_internal_mutable_onion_message () inline private
Definition at line 870 of file proto-packet.pb.h.
References _has_bits_, and onion_message_.
Referenced by _InternalParse(), and mutable_onion_message().
_internal_mutable_padding()
std::string * protomessage::ProtoPacket_OnionHead::_internal_mutable_padding () inline private
Definition at line 939 of file proto-packet.pb.h.
References _has_bits_, and padding_.
Referenced by _InternalParse(), mutable_padding(), and protomessage::ProtoPacket_OnionBody::mutable_padding().
_internal_onion_message()
const std::string & protomessage::ProtoPacket_OnionHead::_internal_onion_message () const inline private
Definition at line 863 of file proto-packet.pb.h.
References onion_message_.
Referenced by _InternalSerialize(), ByteSizeLong(), MergeFrom(), onion_message(), and ProtoPacket_OnionHead().
_internal_onionid()
int32_t protomessage::ProtoPacket_OnionHead::_internal_onionid () const inline private
Definition at line 819 of file proto-packet.pb.h.
References onionid_.
Referenced by _InternalSerialize(), ByteSizeLong(), and onionid().
_internal_padding()
const std::string & protomessage::ProtoPacket_OnionHead::_internal_padding () const inline private
Definition at line 932 of file proto-packet.pb.h.
References padding_.
Referenced by _InternalSerialize(), ByteSizeLong(), MergeFrom(), padding(), protomessage::ProtoPacket_OnionBody::padding(), and ProtoPacket_OnionHead().
_internal_set_onion_message()
void protomessage::ProtoPacket_OnionHead::_internal_set_onion_message (const std::string & value) inline private
Definition at line 866 of file proto-packet.pb.h.
References _has_bits_, and onion_message_.
Referenced by MergeFrom().
_internal_set_onionid()
void protomessage::ProtoPacket_OnionHead::_internal_set_onionid (int32_t value) inline private
Definition at line 826 of file proto-packet.pb.h.
References _has_bits_, and onionid_.
Referenced by set_onionid().
_internal_set_padding()
void protomessage::ProtoPacket_OnionHead::_internal_set_padding (const std::string & value) inline private
Definition at line 935 of file proto-packet.pb.h.
References _has_bits_, and padding_.
Referenced by MergeFrom().
_InternalParse()
const char * protomessage::ProtoPacket_OnionHead::_InternalParse (const char * ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext * ctx) final
Definition at line 271 of file proto-packet.pb.cc.
References _has_bits_, _internal_mutable_onion_message(), _internal_mutable_padding(), CHK_, onionid_, and protomessage::ProtoPacket_OnionHead::_Internal::set_has_onionid().
_InternalSerialize()
uint8_t * protomessage::ProtoPacket_OnionHead::_InternalSerialize (uint8_t * target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream * stream) const final
Definition at line 329 of file proto-packet.pb.cc.
References _internal_has_onion_message(), _internal_has_onionid(), _internal_has_padding(), _internal_onion_message(), _internal_onionid(), and _internal_padding().
ArenaDtor()
void protomessage::ProtoPacket_OnionHead::ArenaDtor (void * object) static private
Definition at line 241 of file proto-packet.pb.cc.
ByteSizeLong()
size_t protomessage::ProtoPacket_OnionHead::ByteSizeLong () const final
Definition at line 361 of file proto-packet.pb.cc.
References _cached_size_, _has_bits_, _internal_onion_message(), _internal_onionid(), and _internal_padding().
Referenced by ns3::SensorNode::ReceivePacket(), and ns3::Sink::SendOnion().
Clear()
void protomessage::ProtoPacket_OnionHead::Clear () final
Definition at line 251 of file proto-packet.pb.cc.
References _has_bits_, onion_message_, onionid_, and padding_.
Referenced by protomessage::ProtoPacket::Clear(), and CopyFrom().
clear_onion_message()
void protomessage::ProtoPacket_OnionHead::clear_onion_message () inline
Definition at line 843 of file proto-packet.pb.h.
References _has_bits_, and onion_message_.
clear_onionid()
void protomessage::ProtoPacket_OnionHead::clear_onionid () inline
Definition at line 815 of file proto-packet.pb.h.
References _has_bits_, and onionid_.
clear_padding()
void protomessage::ProtoPacket_OnionHead::clear_padding () inline
Definition at line 912 of file proto-packet.pb.h.
References _has_bits_, and padding_.
CopyFrom()
void protomessage::ProtoPacket_OnionHead::CopyFrom (const ProtoPacket_OnionHead & from)
Definition at line 429 of file proto-packet.pb.cc.
References Clear(), and MergeFrom().
Referenced by operator=(), protomessage::ProtoPacket_OnionBody::operator=(), protomessage::ProtoPacket_Handshake::operator=(), and protomessage::ProtoPacket::operator=().
default_instance()
static const ProtoPacket_OnionHead& protomessage::ProtoPacket_OnionHead::default_instance () inline static
Definition at line 120 of file proto-packet.pb.h.
References internal_default_instance().
Referenced by GetDescriptor(), protomessage::ProtoPacket_OnionBody::GetDescriptor(), protomessage::ProtoPacket_Handshake::GetDescriptor(), protomessage::ProtoPacket::GetDescriptor(), GetReflection(), protomessage::ProtoPacket_OnionBody::GetReflection(), protomessage::ProtoPacket_Handshake::GetReflection(), and protomessage::ProtoPacket::GetReflection().
descriptor()
static const ::PROTOBUF_NAMESPACE_ID::Descriptor* protomessage::ProtoPacket_OnionHead::descriptor () inline static
Definition at line 111 of file proto-packet.pb.h.
References GetDescriptor().
FullMessageName()
::PROTOBUF_NAMESPACE_ID::StringPiece protomessage::ProtoPacket_OnionHead::FullMessageName () inline static private
Definition at line 181 of file proto-packet.pb.h.
GetCachedSize()
int protomessage::ProtoPacket_OnionHead::GetCachedSize () const inline final
Definition at line 171 of file proto-packet.pb.h.
References _cached_size_.
GetClassData()
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData * protomessage::ProtoPacket_OnionHead::GetClassData () const final
Definition at line 398 of file proto-packet.pb.cc.
References _class_data_.
GetDescriptor()
static const ::PROTOBUF_NAMESPACE_ID::Descriptor* protomessage::ProtoPacket_OnionHead::GetDescriptor () inline static
Definition at line 114 of file proto-packet.pb.h.
References default_instance(), and GetMetadata().
Referenced by descriptor(), protomessage::ProtoPacket_OnionBody::descriptor(), protomessage::ProtoPacket_Handshake::descriptor(), and protomessage::ProtoPacket::descriptor().
GetMetadata()
PROTOBUF_NAMESPACE_ID::Metadata protomessage::ProtoPacket_OnionHead::GetMetadata () const final
Definition at line 459 of file proto-packet.pb.cc.
References descriptor_table_proto_2dpacket_2eproto_getter(), descriptor_table_proto_2dpacket_2eproto_once, and file_level_metadata_proto_2dpacket_2eproto.
Referenced by GetDescriptor(), protomessage::ProtoPacket_OnionBody::GetDescriptor(), protomessage::ProtoPacket_Handshake::GetDescriptor(), protomessage::ProtoPacket::GetDescriptor(), GetReflection(), protomessage::ProtoPacket_OnionBody::GetReflection(), protomessage::ProtoPacket_Handshake::GetReflection(), and protomessage::ProtoPacket::GetReflection().
GetReflection()
static const ::PROTOBUF_NAMESPACE_ID::Reflection* protomessage::ProtoPacket_OnionHead::GetReflection () inline static
Definition at line 117 of file proto-packet.pb.h.
References default_instance(), and GetMetadata().
has_onion_message()
bool protomessage::ProtoPacket_OnionHead::has_onion_message () const inline
Definition at line 840 of file proto-packet.pb.h.
References _internal_has_onion_message().
has_onionid()
bool protomessage::ProtoPacket_OnionHead::has_onionid () const inline
Definition at line 812 of file proto-packet.pb.h.
References _internal_has_onionid().
has_padding()
bool protomessage::ProtoPacket_OnionHead::has_padding () const inline
Definition at line 909 of file proto-packet.pb.h.
References _internal_has_padding().
Referenced by ns3::SensorNode::ProcessOnionHead().
internal_default_instance()
static const ProtoPacket_OnionHead* protomessage::ProtoPacket_OnionHead::internal_default_instance () inline static
Definition at line 123 of file proto-packet.pb.h.
References protomessage::_ProtoPacket_OnionHead_default_instance_.
Referenced by default_instance(), protomessage::ProtoPacket_OnionBody::default_instance(), protomessage::ProtoPacket_Handshake::default_instance(), and protomessage::ProtoPacket::default_instance().
InternalSwap()
void protomessage::ProtoPacket_OnionHead::InternalSwap (ProtoPacket_OnionHead * other) private
Definition at line 440 of file proto-packet.pb.cc.
References _has_bits_, InternalSwap(), onion_message_, onionid_, padding_, and swap.
Referenced by InternalSwap(), operator=(), protomessage::ProtoPacket_OnionBody::operator=(), protomessage::ProtoPacket_Handshake::operator=(), protomessage::ProtoPacket::operator=(), Swap(), protomessage::ProtoPacket_OnionBody::Swap(), protomessage::ProtoPacket_Handshake::Swap(), protomessage::ProtoPacket::Swap(), UnsafeArenaSwap(), protomessage::ProtoPacket_OnionBody::UnsafeArenaSwap(), protomessage::ProtoPacket_Handshake::UnsafeArenaSwap(), and protomessage::ProtoPacket::UnsafeArenaSwap().
IsInitialized()
bool protomessage::ProtoPacket_OnionHead::IsInitialized () const final
Definition at line 436 of file proto-packet.pb.cc.
MergeFrom()
void protomessage::ProtoPacket_OnionHead::MergeFrom (const ProtoPacket_OnionHead & from)
Definition at line 407 of file proto-packet.pb.cc.
References _has_bits_, _internal_onion_message(), _internal_padding(), _internal_set_onion_message(), _internal_set_padding(), and onionid_.
Referenced by CopyFrom(), and MergeImpl().
MergeImpl()
void protomessage::ProtoPacket_OnionHead::MergeImpl (::PROTOBUF_NAMESPACE_ID::Message * to, const ::PROTOBUF_NAMESPACE_ID::Message & from) static private
Definition at line 400 of file proto-packet.pb.cc.
References MergeFrom().
mutable_onion_message()
std::string * protomessage::ProtoPacket_OnionHead::mutable_onion_message () inline
Definition at line 858 of file proto-packet.pb.h.
References _internal_mutable_onion_message().
mutable_padding()
std::string * protomessage::ProtoPacket_OnionHead::mutable_padding () inline
Definition at line 927 of file proto-packet.pb.h.
References _internal_mutable_padding().
New()
ProtoPacket_OnionHead* protomessage::ProtoPacket_OnionHead::New (::PROTOBUF_NAMESPACE_ID::Arena * arena = nullptr) const inline final
Definition at line 154 of file proto-packet.pb.h.
onion_message()
const std::string & protomessage::ProtoPacket_OnionHead::onion_message () const inline
Definition at line 847 of file proto-packet.pb.h.
References _internal_onion_message().
Referenced by ns3::SensorNode::ProcessOnionHead(), and set_allocated_onion_message().
onionid()
int32_t protomessage::ProtoPacket_OnionHead::onionid () const inline
Definition at line 822 of file proto-packet.pb.h.
References _internal_onionid().
Referenced by ns3::SensorNode::ReceivePacket(), and ns3::Sink::ReceivePacket().
operator=() [1/2]
ProtoPacket_OnionHead& protomessage::ProtoPacket_OnionHead::operator= (const ProtoPacket_OnionHead & from) inline
Definition at line 93 of file proto-packet.pb.h.
References CopyFrom().
operator=() [2/2]
ProtoPacket_OnionHead& protomessage::ProtoPacket_OnionHead::operator= (ProtoPacket_OnionHead && from) inline noexcept
Definition at line 97 of file proto-packet.pb.h.
References CopyFrom(), and InternalSwap().
padding()
const std::string & protomessage::ProtoPacket_OnionHead::padding () const inline
Definition at line 916 of file proto-packet.pb.h.
References _internal_padding().
Referenced by ns3::SensorNode::ProcessOnionHead(), set_allocated_padding(), and protomessage::ProtoPacket_OnionBody::set_allocated_padding().
RegisterArenaDtor()
void protomessage::ProtoPacket_OnionHead::RegisterArenaDtor (::PROTOBUF_NAMESPACE_ID::Arena * arena) inline private
Definition at line 245 of file proto-packet.pb.cc.
Referenced by ProtoPacket_OnionHead().
release_onion_message()
std::string * protomessage::ProtoPacket_OnionHead::release_onion_message () inline
Definition at line 874 of file proto-packet.pb.h.
References _has_bits_, _internal_has_onion_message(), and onion_message_.
release_padding()
std::string * protomessage::ProtoPacket_OnionHead::release_padding () inline
Definition at line 943 of file proto-packet.pb.h.
References _has_bits_, _internal_has_padding(), and padding_.
set_allocated_onion_message()
void protomessage::ProtoPacket_OnionHead::set_allocated_onion_message (std::string * onion_message) inline
Definition at line 888 of file proto-packet.pb.h.
References _has_bits_, onion_message(), and onion_message_.
set_allocated_padding()
void protomessage::ProtoPacket_OnionHead::set_allocated_padding (std::string * padding) inline
Definition at line 957 of file proto-packet.pb.h.
References _has_bits_, padding(), and padding_.
set_onion_message() [1/2]
template<typename ArgT0 = const std::string&, typename... ArgT> void protomessage::ProtoPacket_OnionHead::set_onion_message (ArgT0 && arg0, ArgT... args)
Referenced by ns3::SensorNode::ProcessOnionHead(), and ns3::Sink::SendOnion().
set_onion_message() [2/2]
template<typename ArgT0 , typename... ArgT> PROTOBUF_ALWAYS_INLINE void protomessage::ProtoPacket_OnionHead::set_onion_message (ArgT0 && arg0, ArgT... args) inline
Definition at line 853 of file proto-packet.pb.h.
References _has_bits_, and onion_message_.
set_onionid()
void protomessage::ProtoPacket_OnionHead::set_onionid (int32_t value) inline
Definition at line 830 of file proto-packet.pb.h.
References _internal_set_onionid().
Referenced by ns3::Sink::SendOnion().
set_padding() [1/2]
template<typename ArgT0 = const std::string&, typename... ArgT> void protomessage::ProtoPacket_OnionHead::set_padding (ArgT0 && arg0, ArgT... args)
Referenced by ns3::SensorNode::ProcessOnionHead(), and ns3::Sink::SendOnion().
set_padding() [2/2]
template<typename ArgT0 , typename... ArgT> PROTOBUF_ALWAYS_INLINE void protomessage::ProtoPacket_OnionHead::set_padding (ArgT0 && arg0, ArgT... args) inline
Definition at line 922 of file proto-packet.pb.h.
References _has_bits_, and padding_.
SetCachedSize()
void protomessage::ProtoPacket_OnionHead::SetCachedSize (int size) const final private
Definition at line 247 of file proto-packet.pb.cc.
References _cached_size_.
SharedCtor()
void protomessage::ProtoPacket_OnionHead::SharedCtor () inline private
Definition at line 216 of file proto-packet.pb.cc.
References onion_message_, onionid_, and padding_.
Referenced by ProtoPacket_OnionHead().
SharedDtor()
void protomessage::ProtoPacket_OnionHead::SharedDtor () inline private
Definition at line 235 of file proto-packet.pb.cc.
References onion_message_, and padding_.
Referenced by ~ProtoPacket_OnionHead().
Swap()
void protomessage::ProtoPacket_OnionHead::Swap (ProtoPacket_OnionHead * other) inline
Definition at line 133 of file proto-packet.pb.h.
References InternalSwap().
UnsafeArenaSwap()
void protomessage::ProtoPacket_OnionHead::UnsafeArenaSwap (ProtoPacket_OnionHead * other) inline
Definition at line 146 of file proto-packet.pb.h.
References InternalSwap().
Friends And Related Function Documentation
::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper
template<typename T > friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper friend
Definition at line 257 of file proto-packet.pb.h.
::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata
friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata friend
Definition at line 180 of file proto-packet.pb.h.
::TableStruct_proto_2dpacket_2eproto
friend struct ::TableStruct_proto_2dpacket_2eproto friend
Definition at line 267 of file proto-packet.pb.h.
swap
void swap (ProtoPacket_OnionHead & a, ProtoPacket_OnionHead & b) friend
Definition at line 130 of file proto-packet.pb.h.
Referenced by InternalSwap().
Member Data Documentation
_cached_size_
mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize protomessage::ProtoPacket_OnionHead::_cached_size_ private
Definition at line 263 of file proto-packet.pb.h.
Referenced by ByteSizeLong(), GetCachedSize(), protomessage::ProtoPacket_OnionBody::GetCachedSize(), protomessage::ProtoPacket_Handshake::GetCachedSize(), protomessage::ProtoPacket::GetCachedSize(), and SetCachedSize().
_class_data_
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData protomessage::ProtoPacket_OnionHead::_class_data_ static
Initial value:
= {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    ProtoPacket_OnionHead::MergeImpl
}
Definition at line 192 of file proto-packet.pb.h.
Referenced by GetClassData().
_has_bits_
::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> protomessage::ProtoPacket_OnionHead::_has_bits_ private
Definition at line 262 of file proto-packet.pb.h.
Referenced by protomessage::ProtoPacket_OnionBody::_internal_has_aggregatedvalue(), protomessage::ProtoPacket::_internal_has_h_shake(), protomessage::ProtoPacket::_internal_has_o_body(), protomessage::ProtoPacket::_internal_has_o_head(), _internal_has_onion_message(), _internal_has_onionid(), _internal_has_padding(), protomessage::ProtoPacket_OnionBody::_internal_has_padding(), protomessage::ProtoPacket_Handshake::_internal_has_publickey(), protomessage::ProtoPacket::_internal_mutable_h_shake(), protomessage::ProtoPacket::_internal_mutable_o_body(), protomessage::ProtoPacket::_internal_mutable_o_head(), _internal_mutable_onion_message(), _internal_mutable_padding(), protomessage::ProtoPacket_OnionBody::_internal_mutable_padding(), protomessage::ProtoPacket_Handshake::_internal_mutable_publickey(), protomessage::ProtoPacket_OnionBody::_internal_set_aggregatedvalue(), _internal_set_onion_message(), _internal_set_onionid(), _internal_set_padding(), protomessage::ProtoPacket_OnionBody::_internal_set_padding(), protomessage::ProtoPacket_Handshake::_internal_set_publickey(), _InternalParse(), ByteSizeLong(), Clear(), protomessage::ProtoPacket_OnionBody::clear_aggregatedvalue(), protomessage::ProtoPacket::clear_h_shake(), protomessage::ProtoPacket::clear_o_body(), protomessage::ProtoPacket::clear_o_head(), clear_onion_message(), clear_onionid(), clear_padding(), protomessage::ProtoPacket_OnionBody::clear_padding(), protomessage::ProtoPacket_Handshake::clear_publickey(), InternalSwap(), MergeFrom(), protomessage::ProtoPacket::release_h_shake(), protomessage::ProtoPacket::release_o_body(), protomessage::ProtoPacket::release_o_head(), release_onion_message(), release_padding(), protomessage::ProtoPacket_OnionBody::release_padding(), protomessage::ProtoPacket_Handshake::release_publickey(), protomessage::ProtoPacket::set_allocated_h_shake(), protomessage::ProtoPacket::set_allocated_o_body(), protomessage::ProtoPacket::set_allocated_o_head(), set_allocated_onion_message(), set_allocated_padding(), protomessage::ProtoPacket_OnionBody::set_allocated_padding(), protomessage::ProtoPacket_Handshake::set_allocated_publickey(), set_onion_message(), set_padding(), protomessage::ProtoPacket_OnionBody::set_padding(), protomessage::ProtoPacket_Handshake::set_publickey(), protomessage::ProtoPacket::unsafe_arena_release_h_shake(), protomessage::ProtoPacket::unsafe_arena_release_o_body(), protomessage::ProtoPacket::unsafe_arena_release_o_head(), protomessage::ProtoPacket::unsafe_arena_set_allocated_h_shake(), protomessage::ProtoPacket::unsafe_arena_set_allocated_o_body(), and protomessage::ProtoPacket::unsafe_arena_set_allocated_o_head().
kIndexInFileMessages
constexpr int protomessage::ProtoPacket_OnionHead::kIndexInFileMessages static constexpr
Initial value:
=
    0
Definition at line 127 of file proto-packet.pb.h.
onion_message_
::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr protomessage::ProtoPacket_OnionHead::onion_message_ private
Definition at line 264 of file proto-packet.pb.h.
Referenced by _internal_mutable_onion_message(), _internal_onion_message(), _internal_set_onion_message(), Clear(), clear_onion_message(), InternalSwap(), ProtoPacket_OnionHead(), release_onion_message(), set_allocated_onion_message(), set_onion_message(), SharedCtor(), and SharedDtor().
onionid_
int32_t protomessage::ProtoPacket_OnionHead::onionid_ private
Definition at line 266 of file proto-packet.pb.h.
Referenced by _internal_onionid(), _internal_set_onionid(), _InternalParse(), Clear(), clear_onionid(), InternalSwap(), MergeFrom(), ProtoPacket_OnionHead(), and SharedCtor().
padding_
::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr protomessage::ProtoPacket_OnionHead::padding_ private
Definition at line 265 of file proto-packet.pb.h.
Referenced by _internal_mutable_padding(), protomessage::ProtoPacket_OnionBody::_internal_mutable_padding(), _internal_padding(), protomessage::ProtoPacket_OnionBody::_internal_padding(), _internal_set_padding(), protomessage::ProtoPacket_OnionBody::_internal_set_padding(), Clear(), clear_padding(), protomessage::ProtoPacket_OnionBody::clear_padding(), InternalSwap(), ProtoPacket_OnionHead(), release_padding(), protomessage::ProtoPacket_OnionBody::release_padding(), set_allocated_padding(), protomessage::ProtoPacket_OnionBody::set_allocated_padding(), set_padding(), protomessage::ProtoPacket_OnionBody::set_padding(), SharedCtor(), and SharedDtor().
The documentation for this class was generated from the following files:
src/onion_routing_wsn/protobuf/proto-packet.pb.h
src/onion_routing_wsn/protobuf/proto-packet.pb.cc