ns-3: ns3::SensorNodeHelper Class Reference
ns3::SensorNodeHelper Class Reference
Application-helper
Helper class for the creation of SensorNode applications.
#include "sensornode-helper.h"
Public Member Functions
SensorNodeHelper ()
Default constructor.
SensorNodeHelper (Ipv4Address address, Ptr< OutputManager > outputManager, Ptr< OnionValidator > onionValidator)
Constructor with attributes to set basic attributes of sensor nodes.
~SensorNodeHelper ()
Default constructor.
ApplicationContainer Install (NodeContainer c) const
Ptr< Application > InstallPriv (Ptr< Node > node) const
void SetAttribute (std::string name, const AttributeValue &value)
Setter of individual attributes.
Static Public Member Functions
static TypeId GetTypeId (void)
Register this type.
Private Attributes
ObjectFactory m_factory
factory object
uint16_t m_onionTimeout
A watchdog timer set to abort onion messagess, if the timer elepses before the onion returns back to the sink node.
Ptr< OnionValidator > m_onionValidator
Manage onions and when to abort them.
Ptr< OutputManager > m_outputManager
Manage the output of the simulation.
Ipv4Address m_sinkAddress
Ipv4 address of the sink node.
Detailed Description
Helper class for the creation of SensorNode applications.
Definition at line 56 of file sensornode-helper.h.
Constructor & Destructor Documentation
SensorNodeHelper() [1/2]
ns3::SensorNodeHelper::SensorNodeHelper ()
Default constructor.
Definition at line 39 of file sensornode-helper.cc.
References m_factory.
SensorNodeHelper() [2/2]
ns3::SensorNodeHelper::SensorNodeHelper (Ipv4Address address, Ptr< OutputManager > outputManager, Ptr< OnionValidator > onionValidator)
Constructor with attributes to set basic attributes of sensor nodes.
Definition at line 44 of file sensornode-helper.cc.
References m_factory, m_onionValidator, and m_outputManager.
~SensorNodeHelper()
ns3::SensorNodeHelper::~SensorNodeHelper ()
Default constructor.
Definition at line 54 of file sensornode-helper.cc.
Member Function Documentation
GetTypeId()
TypeId ns3::SensorNodeHelper::GetTypeId (void) static
Register this type.
Returns
The object TypeId.
Definition at line 32 of file sensornode-helper.cc.
Install()
ApplicationContainer ns3::SensorNodeHelper::Install (NodeContainer c) const
Definition at line 65 of file sensornode-helper.cc.
References InstallPriv().
Referenced by WsnConstructor::InstallApplications().
InstallPriv()
Ptr< Application > ns3::SensorNodeHelper::InstallPriv (Ptr< Node > node) const
Definition at line 77 of file sensornode-helper.cc.
References m_factory.
Referenced by Install().
SetAttribute()
void ns3::SensorNodeHelper::SetAttribute (std::string name, const AttributeValue & value)
Setter of individual attributes.
Definition at line 59 of file sensornode-helper.cc.
References m_factory.
Member Data Documentation
m_factory
ObjectFactory ns3::SensorNodeHelper::m_factory private
factory object
Definition at line 116 of file sensornode-helper.h.
Referenced by InstallPriv(), SensorNodeHelper(), and SetAttribute().
m_onionTimeout
uint16_t ns3::SensorNodeHelper::m_onionTimeout private
A watchdog timer set to abort onion messagess, if the timer elepses before the onion returns back to the sink node.
Definition at line 115 of file sensornode-helper.h.
m_onionValidator
Ptr<OnionValidator> ns3::SensorNodeHelper::m_onionValidator private
Manage onions and when to abort them.
Definition at line 113 of file sensornode-helper.h.
Referenced by SensorNodeHelper().
m_outputManager
Ptr<OutputManager> ns3::SensorNodeHelper::m_outputManager private
Manage the output of the simulation.
Definition at line 112 of file sensornode-helper.h.
Referenced by SensorNodeHelper().
m_sinkAddress
Ipv4Address ns3::SensorNodeHelper::m_sinkAddress private
Ipv4 address of the sink node.
Definition at line 111 of file sensornode-helper.h.
The documentation for this class was generated from the following files:
src/onion_routing_wsn/helper/sensornode-helper.h
src/onion_routing_wsn/helper/sensornode-helper.cc