ns-3: protomessage::ProtoPacket_OnionBody Class Reference
protomessage::ProtoPacket_OnionBody Class Reference final
#include "proto-packet.pb.h"
Classes
class _Internal
Public Types
enum : int { kPaddingFieldNumber = 2, kAggregatedValueFieldNumber = 1 }
Public Member Functions
ProtoPacket_OnionBody ()
constexpr ProtoPacket_OnionBody (::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
ProtoPacket_OnionBody (const ProtoPacket_OnionBody &from)
ProtoPacket_OnionBody (ProtoPacket_OnionBody &&from) noexcept
~ProtoPacket_OnionBody () override
const char * _InternalParse (const char *ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext *ctx) final
uint8_t * _InternalSerialize (uint8_t *target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream *stream) const final
int32_t aggregatedvalue () const
size_t ByteSizeLong () const final
PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear () final
void clear_aggregatedvalue ()
void clear_padding ()
void CopyFrom (const ProtoPacket_OnionBody &from)
int GetCachedSize () const final
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData * GetClassData () const final
::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata () const final
bool has_aggregatedvalue () const
bool has_padding () const
bool IsInitialized () const final
void MergeFrom (const ProtoPacket_OnionBody &from)
std::string * mutable_padding ()
ProtoPacket_OnionBody * New (::PROTOBUF_NAMESPACE_ID::Arena *arena=nullptr) const final
ProtoPacket_OnionBody & operator= (const ProtoPacket_OnionBody &from)
ProtoPacket_OnionBody & operator= (ProtoPacket_OnionBody &&from) noexcept
const std::string & padding () const
PROTOBUF_NODISCARD std::string * release_padding ()
void set_aggregatedvalue (int32_t value)
void set_allocated_padding (std::string *padding)
template<typename ArgT0 = const std::string&, typename... ArgT>
void set_padding (ArgT0 &&arg0, ArgT... args)
template<typename ArgT0 , typename... ArgT>
PROTOBUF_ALWAYS_INLINE void set_padding (ArgT0 &&arg0, ArgT... args)
void Swap (ProtoPacket_OnionBody *other)
void UnsafeArenaSwap (ProtoPacket_OnionBody *other)
Static Public Member Functions
static const ProtoPacket_OnionBody & default_instance ()
static const ::PROTOBUF_NAMESPACE_ID::Descriptor * descriptor ()
static const ::PROTOBUF_NAMESPACE_ID::Descriptor * GetDescriptor ()
static const ::PROTOBUF_NAMESPACE_ID::Reflection * GetReflection ()
static const ProtoPacket_OnionBody * internal_default_instance ()
Static Public Attributes
static const ClassData _class_data_
static constexpr int kIndexInFileMessages
Protected Member Functions
ProtoPacket_OnionBody (::PROTOBUF_NAMESPACE_ID::Arena *arena, bool is_message_owned=false)
Private Types
typedef void DestructorSkippable_
typedef void InternalArenaConstructable_
Private Member Functions
int32_t _internal_aggregatedvalue () const
bool _internal_has_aggregatedvalue () const
bool _internal_has_padding () const
std::string * _internal_mutable_padding ()
const std::string & _internal_padding () const
void _internal_set_aggregatedvalue (int32_t value)
PROTOBUF_ALWAYS_INLINE void _internal_set_padding (const std::string &value)
void InternalSwap (ProtoPacket_OnionBody *other)
void RegisterArenaDtor (::PROTOBUF_NAMESPACE_ID::Arena *arena)
void SetCachedSize (int size) const final
void SharedCtor ()
void SharedDtor ()
Static Private Member Functions
static void ArenaDtor (void *object)
::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName ()
static void MergeImpl (::PROTOBUF_NAMESPACE_ID::Message *to, const ::PROTOBUF_NAMESPACE_ID::Message &from)
Private Attributes
mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_
::PROTOBUF_NAMESPACE_ID::internal::HasBits< 1 > _has_bits_
int32_t aggregatedvalue_
::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr padding_
Friends
template<typename T >
class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper
class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata
struct ::TableStruct_proto_2dpacket_2eproto
void swap (ProtoPacket_OnionBody &a, ProtoPacket_OnionBody &b)
Detailed Description
Definition at line 271 of file proto-packet.pb.h.
Member Typedef Documentation
DestructorSkippable_
typedef void protomessage::ProtoPacket_OnionBody::DestructorSkippable_ private
Definition at line 433 of file proto-packet.pb.h.
InternalArenaConstructable_
typedef void protomessage::ProtoPacket_OnionBody::InternalArenaConstructable_ private
Definition at line 432 of file proto-packet.pb.h.
Member Enumeration Documentation
anonymous enum
anonymous enum : int
Enumerator
kPaddingFieldNumber
kAggregatedValueFieldNumber
Definition at line 392 of file proto-packet.pb.h.
Constructor & Destructor Documentation
ProtoPacket_OnionBody() [1/5]
protomessage::ProtoPacket_OnionBody::ProtoPacket_OnionBody () inline
Definition at line 274 of file proto-packet.pb.h.
~ProtoPacket_OnionBody()
protomessage::ProtoPacket_OnionBody::~ProtoPacket_OnionBody () override
Definition at line 511 of file proto-packet.pb.cc.
References SharedDtor().
ProtoPacket_OnionBody() [2/5]
constexpr protomessage::ProtoPacket_OnionBody::ProtoPacket_OnionBody (::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized) explicit constexpr
Definition at line 34 of file proto-packet.pb.cc.
ProtoPacket_OnionBody() [3/5]
protomessage::ProtoPacket_OnionBody::ProtoPacket_OnionBody (const ProtoPacket_OnionBody & from)
Definition at line 487 of file proto-packet.pb.cc.
References _internal_has_padding(), _internal_padding(), aggregatedvalue_, and padding_.
ProtoPacket_OnionBody() [4/5]
protomessage::ProtoPacket_OnionBody::ProtoPacket_OnionBody (ProtoPacket_OnionBody && from) inline noexcept
Definition at line 279 of file proto-packet.pb.h.
ProtoPacket_OnionBody() [5/5]
protomessage::ProtoPacket_OnionBody::ProtoPacket_OnionBody (::PROTOBUF_NAMESPACE_ID::Arena * arena, bool is_message_owned = false) explicit protected
Definition at line 478 of file proto-packet.pb.cc.
References RegisterArenaDtor(), and SharedCtor().
Member Function Documentation
_internal_aggregatedvalue()
int32_t protomessage::ProtoPacket_OnionBody::_internal_aggregatedvalue () const inline private
Definition at line 989 of file proto-packet.pb.h.
Referenced by _InternalSerialize(), and ByteSizeLong().
_internal_has_aggregatedvalue()
bool protomessage::ProtoPacket_OnionBody::_internal_has_aggregatedvalue () const inline private
Definition at line 978 of file proto-packet.pb.h.
References protomessage::ProtoPacket_OnionHead::_has_bits_.
Referenced by _InternalSerialize().
_internal_has_padding()
bool protomessage::ProtoPacket_OnionBody::_internal_has_padding () const inline private
Definition at line 1006 of file proto-packet.pb.h.
References protomessage::ProtoPacket_OnionHead::_has_bits_.
Referenced by _InternalSerialize(), and ProtoPacket_OnionBody().
_internal_mutable_padding()
std::string * protomessage::ProtoPacket_OnionBody::_internal_mutable_padding () inline private
Definition at line 1040 of file proto-packet.pb.h.
References protomessage::ProtoPacket_OnionHead::_has_bits_, and protomessage::ProtoPacket_OnionHead::padding_.
Referenced by _InternalParse().
_internal_padding()
const std::string & protomessage::ProtoPacket_OnionBody::_internal_padding () const inline private
Definition at line 1033 of file proto-packet.pb.h.
References protomessage::ProtoPacket_OnionHead::padding_.
Referenced by _InternalSerialize(), ByteSizeLong(), MergeFrom(), and ProtoPacket_OnionBody().
_internal_set_aggregatedvalue()
void protomessage::ProtoPacket_OnionBody::_internal_set_aggregatedvalue (int32_t value) inline private
Definition at line 996 of file proto-packet.pb.h.
References protomessage::ProtoPacket_OnionHead::_has_bits_.
_internal_set_padding()
void protomessage::ProtoPacket_OnionBody::_internal_set_padding (const std::string & value) inline private
Definition at line 1036 of file proto-packet.pb.h.
References protomessage::ProtoPacket_OnionHead::_has_bits_, and protomessage::ProtoPacket_OnionHead::padding_.
Referenced by MergeFrom().
_InternalParse()
const char * protomessage::ProtoPacket_OnionBody::_InternalParse (const char * ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext * ctx) final
Definition at line 548 of file proto-packet.pb.cc.
References _has_bits_, _internal_mutable_padding(), aggregatedvalue_, CHK_, and protomessage::ProtoPacket_OnionBody::_Internal::set_has_aggregatedvalue().
_InternalSerialize()
uint8_t * protomessage::ProtoPacket_OnionBody::_InternalSerialize (uint8_t * target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream * stream) const final
Definition at line 597 of file proto-packet.pb.cc.
References _internal_aggregatedvalue(), _internal_has_aggregatedvalue(), _internal_has_padding(), and _internal_padding().
aggregatedvalue()
int32_t protomessage::ProtoPacket_OnionBody::aggregatedvalue () const inline
Definition at line 992 of file proto-packet.pb.h.
Referenced by ns3::SensorNode::ProcessOnionBody().
ArenaDtor()
void protomessage::ProtoPacket_OnionBody::ArenaDtor (void * object) static private
Definition at line 523 of file proto-packet.pb.cc.
ByteSizeLong()
size_t protomessage::ProtoPacket_OnionBody::ByteSizeLong () const final
Definition at line 623 of file proto-packet.pb.cc.
References _cached_size_, _has_bits_, _internal_aggregatedvalue(), and _internal_padding().
Referenced by ns3::SensorNode::ReceivePacket(), and ns3::Sink::SendOnion().
Clear()
void protomessage::ProtoPacket_OnionBody::Clear () final
Definition at line 533 of file proto-packet.pb.cc.
References _has_bits_, aggregatedvalue_, and padding_.
Referenced by protomessage::ProtoPacket::Clear(), and CopyFrom().
clear_aggregatedvalue()
void protomessage::ProtoPacket_OnionBody::clear_aggregatedvalue () inline
Definition at line 985 of file proto-packet.pb.h.
References protomessage::ProtoPacket_OnionHead::_has_bits_.
clear_padding()
void protomessage::ProtoPacket_OnionBody::clear_padding () inline
Definition at line 1013 of file proto-packet.pb.h.
References protomessage::ProtoPacket_OnionHead::_has_bits_, and protomessage::ProtoPacket_OnionHead::padding_.
CopyFrom()
void protomessage::ProtoPacket_OnionBody::CopyFrom (const ProtoPacket_OnionBody & from)
Definition at line 681 of file proto-packet.pb.cc.
References Clear(), and MergeFrom().
default_instance()
static const ProtoPacket_OnionBody& protomessage::ProtoPacket_OnionBody::default_instance () inline static
Definition at line 311 of file proto-packet.pb.h.
References protomessage::ProtoPacket_OnionHead::internal_default_instance().
descriptor()
static const ::PROTOBUF_NAMESPACE_ID::Descriptor* protomessage::ProtoPacket_OnionBody::descriptor () inline static
Definition at line 302 of file proto-packet.pb.h.
References protomessage::ProtoPacket_OnionHead::GetDescriptor().
FullMessageName()
::PROTOBUF_NAMESPACE_ID::StringPiece protomessage::ProtoPacket_OnionBody::FullMessageName () inline static private
Definition at line 372 of file proto-packet.pb.h.
GetCachedSize()
int protomessage::ProtoPacket_OnionBody::GetCachedSize () const inline final
Definition at line 362 of file proto-packet.pb.h.
References protomessage::ProtoPacket_OnionHead::_cached_size_.
GetClassData()
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData * protomessage::ProtoPacket_OnionBody::GetClassData () const final
Definition at line 653 of file proto-packet.pb.cc.
References _class_data_.
GetDescriptor()
static const ::PROTOBUF_NAMESPACE_ID::Descriptor* protomessage::ProtoPacket_OnionBody::GetDescriptor () inline static
Definition at line 305 of file proto-packet.pb.h.
References protomessage::ProtoPacket_OnionHead::default_instance(), and protomessage::ProtoPacket_OnionHead::GetMetadata().
GetMetadata()
PROTOBUF_NAMESPACE_ID::Metadata protomessage::ProtoPacket_OnionBody::GetMetadata () const final
Definition at line 706 of file proto-packet.pb.cc.
References descriptor_table_proto_2dpacket_2eproto_getter(), descriptor_table_proto_2dpacket_2eproto_once, and file_level_metadata_proto_2dpacket_2eproto.
GetReflection()
static const ::PROTOBUF_NAMESPACE_ID::Reflection* protomessage::ProtoPacket_OnionBody::GetReflection () inline static
Definition at line 308 of file proto-packet.pb.h.
References protomessage::ProtoPacket_OnionHead::default_instance(), and protomessage::ProtoPacket_OnionHead::GetMetadata().
has_aggregatedvalue()
bool protomessage::ProtoPacket_OnionBody::has_aggregatedvalue () const inline
Definition at line 982 of file proto-packet.pb.h.
Referenced by ns3::SensorNode::ProcessOnionBody().
has_padding()
bool protomessage::ProtoPacket_OnionBody::has_padding () const inline
Definition at line 1010 of file proto-packet.pb.h.
References protomessage::ProtoPacket_OnionHead::_internal_has_padding().
internal_default_instance()
static const ProtoPacket_OnionBody* protomessage::ProtoPacket_OnionBody::internal_default_instance () inline static
Definition at line 314 of file proto-packet.pb.h.
References protomessage::_ProtoPacket_OnionBody_default_instance_.
InternalSwap()
void protomessage::ProtoPacket_OnionBody::InternalSwap (ProtoPacket_OnionBody * other) private
Definition at line 692 of file proto-packet.pb.cc.
References _has_bits_, aggregatedvalue_, InternalSwap(), padding_, and swap.
Referenced by InternalSwap().
IsInitialized()
bool protomessage::ProtoPacket_OnionBody::IsInitialized () const final
Definition at line 688 of file proto-packet.pb.cc.
MergeFrom()
void protomessage::ProtoPacket_OnionBody::MergeFrom (const ProtoPacket_OnionBody & from)
Definition at line 662 of file proto-packet.pb.cc.
References _has_bits_, _internal_padding(), _internal_set_padding(), and aggregatedvalue_.
Referenced by CopyFrom(), protomessage::ProtoPacket::MergeFrom(), and MergeImpl().
MergeImpl()
void protomessage::ProtoPacket_OnionBody::MergeImpl (::PROTOBUF_NAMESPACE_ID::Message * to, const ::PROTOBUF_NAMESPACE_ID::Message & from) static private
Definition at line 655 of file proto-packet.pb.cc.
References MergeFrom().
mutable_padding()
std::string * protomessage::ProtoPacket_OnionBody::mutable_padding () inline
Definition at line 1028 of file proto-packet.pb.h.
References protomessage::ProtoPacket_OnionHead::_internal_mutable_padding().
New()
ProtoPacket_OnionBody* protomessage::ProtoPacket_OnionBody::New (::PROTOBUF_NAMESPACE_ID::Arena * arena = nullptr) const inline final
Definition at line 345 of file proto-packet.pb.h.
operator=() [1/2]
ProtoPacket_OnionBody& protomessage::ProtoPacket_OnionBody::operator= (const ProtoPacket_OnionBody & from) inline
Definition at line 284 of file proto-packet.pb.h.
References protomessage::ProtoPacket_OnionHead::CopyFrom().
operator=() [2/2]
ProtoPacket_OnionBody& protomessage::ProtoPacket_OnionBody::operator= (ProtoPacket_OnionBody && from) inline noexcept
Definition at line 288 of file proto-packet.pb.h.
References protomessage::ProtoPacket_OnionHead::CopyFrom(), and protomessage::ProtoPacket_OnionHead::InternalSwap().
padding()
const std::string & protomessage::ProtoPacket_OnionBody::padding () const inline
Definition at line 1017 of file proto-packet.pb.h.
References protomessage::ProtoPacket_OnionHead::_internal_padding().
RegisterArenaDtor()
void protomessage::ProtoPacket_OnionBody::RegisterArenaDtor (::PROTOBUF_NAMESPACE_ID::Arena * arena) inline private
Definition at line 527 of file proto-packet.pb.cc.
Referenced by ProtoPacket_OnionBody().
release_padding()
std::string * protomessage::ProtoPacket_OnionBody::release_padding () inline
Definition at line 1044 of file proto-packet.pb.h.
References protomessage::ProtoPacket_OnionHead::_has_bits_, protomessage::ProtoPacket_OnionHead::_internal_has_padding(), and protomessage::ProtoPacket_OnionHead::padding_.
set_aggregatedvalue()
void protomessage::ProtoPacket_OnionBody::set_aggregatedvalue (int32_t value) inline
Definition at line 1000 of file proto-packet.pb.h.
Referenced by ns3::SensorNode::ProcessOnionBody(), and ns3::Sink::SendOnion().
set_allocated_padding()
void protomessage::ProtoPacket_OnionBody::set_allocated_padding (std::string * padding) inline
Definition at line 1058 of file proto-packet.pb.h.
References protomessage::ProtoPacket_OnionHead::_has_bits_, protomessage::ProtoPacket_OnionHead::padding(), and protomessage::ProtoPacket_OnionHead::padding_.
set_padding() [1/2]
template<typename ArgT0 = const std::string&, typename... ArgT> void protomessage::ProtoPacket_OnionBody::set_padding (ArgT0 && arg0, ArgT... args)
Referenced by ns3::Sink::SendOnion().
set_padding() [2/2]
template<typename ArgT0 , typename... ArgT> PROTOBUF_ALWAYS_INLINE void protomessage::ProtoPacket_OnionBody::set_padding (ArgT0 && arg0, ArgT... args) inline
Definition at line 1023 of file proto-packet.pb.h.
References protomessage::ProtoPacket_OnionHead::_has_bits_, and protomessage::ProtoPacket_OnionHead::padding_.
SetCachedSize()
void protomessage::ProtoPacket_OnionBody::SetCachedSize (int size) const final private
Definition at line 529 of file proto-packet.pb.cc.
References _cached_size_.
SharedCtor()
void protomessage::ProtoPacket_OnionBody::SharedCtor () inline private
Definition at line 503 of file proto-packet.pb.cc.
References aggregatedvalue_, and padding_.
Referenced by ProtoPacket_OnionBody().
SharedDtor()
void protomessage::ProtoPacket_OnionBody::SharedDtor () inline private
Definition at line 518 of file proto-packet.pb.cc.
References padding_.
Referenced by ~ProtoPacket_OnionBody().
Swap()
void protomessage::ProtoPacket_OnionBody::Swap (ProtoPacket_OnionBody * other) inline
Definition at line 324 of file proto-packet.pb.h.
References protomessage::ProtoPacket_OnionHead::InternalSwap().
UnsafeArenaSwap()
void protomessage::ProtoPacket_OnionBody::UnsafeArenaSwap (ProtoPacket_OnionBody * other) inline
Definition at line 337 of file proto-packet.pb.h.
References protomessage::ProtoPacket_OnionHead::InternalSwap().
Friends And Related Function Documentation
::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper
template<typename T > friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper friend
Definition at line 429 of file proto-packet.pb.h.
::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata
friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata friend
Definition at line 371 of file proto-packet.pb.h.
::TableStruct_proto_2dpacket_2eproto
friend struct ::TableStruct_proto_2dpacket_2eproto friend
Definition at line 438 of file proto-packet.pb.h.
swap
void swap (ProtoPacket_OnionBody & a, ProtoPacket_OnionBody & b) friend
Definition at line 321 of file proto-packet.pb.h.
Referenced by InternalSwap().
Member Data Documentation
_cached_size_
mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize protomessage::ProtoPacket_OnionBody::_cached_size_ private
Definition at line 435 of file proto-packet.pb.h.
Referenced by ByteSizeLong(), and SetCachedSize().
_class_data_
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData protomessage::ProtoPacket_OnionBody::_class_data_ static
Initial value:
= {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    ProtoPacket_OnionBody::MergeImpl
}
Definition at line 383 of file proto-packet.pb.h.
Referenced by GetClassData().
_has_bits_
::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> protomessage::ProtoPacket_OnionBody::_has_bits_ private
Definition at line 434 of file proto-packet.pb.h.
Referenced by _InternalParse(), ByteSizeLong(), Clear(), InternalSwap(), and MergeFrom().
aggregatedvalue_
int32_t protomessage::ProtoPacket_OnionBody::aggregatedvalue_ private
Definition at line 437 of file proto-packet.pb.h.
Referenced by _InternalParse(), Clear(), InternalSwap(), MergeFrom(), ProtoPacket_OnionBody(), and SharedCtor().
kIndexInFileMessages
constexpr int protomessage::ProtoPacket_OnionBody::kIndexInFileMessages static constexpr
Initial value:
=
    1
Definition at line 318 of file proto-packet.pb.h.
padding_
::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr protomessage::ProtoPacket_OnionBody::padding_ private
Definition at line 436 of file proto-packet.pb.h.
Referenced by Clear(), InternalSwap(), ProtoPacket_OnionBody(), SharedCtor(), and SharedDtor().
The documentation for this class was generated from the following files:
src/onion_routing_wsn/protobuf/proto-packet.pb.h
src/onion_routing_wsn/protobuf/proto-packet.pb.cc