ns-3: src/onion_routing_wsn/protobuf/proto-packet.pb.cc File Reference
proto-packet.pb.cc File Reference
#include "proto-packet.pb.h"
#include <algorithm>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
#include <google/protobuf/port_def.inc>
#include <google/protobuf/port_undef.inc>
Classes
class protomessage::ProtoPacket::_Internal
class protomessage::ProtoPacket_Handshake::_Internal
class protomessage::ProtoPacket_OnionBody::_Internal
class protomessage::ProtoPacket_OnionHead::_Internal
struct protomessage::ProtoPacket_HandshakeDefaultTypeInternal
struct protomessage::ProtoPacket_OnionBodyDefaultTypeInternal
struct protomessage::ProtoPacket_OnionHeadDefaultTypeInternal
struct protomessage::ProtoPacketDefaultTypeInternal
Namespaces
protomessage
Macros
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
Functions
template<>
PROTOBUF_NOINLINE ::protomessage::ProtoPacket * Arena::CreateMaybeMessage< ::protomessage::ProtoPacket > (Arena *arena)
template<>
PROTOBUF_NOINLINE ::protomessage::ProtoPacket_Handshake * Arena::CreateMaybeMessage< ::protomessage::ProtoPacket_Handshake > (Arena *arena)
template<>
PROTOBUF_NOINLINE ::protomessage::ProtoPacket_OnionBody * Arena::CreateMaybeMessage< ::protomessage::ProtoPacket_OnionBody > (Arena *arena)
template<>
PROTOBUF_NAMESPACE_OPEN PROTOBUF_NOINLINE ::protomessage::ProtoPacket_OnionHead * Arena::CreateMaybeMessage< ::protomessage::ProtoPacket_OnionHead > (Arena *arena)
const PROTOBUF_ATTRIBUTE_WEAK ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable * descriptor_table_proto_2dpacket_2eproto_getter ()
const uint32_t TableStruct_proto_2dpacket_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE (protodesc_cold)
Variables
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT ProtoPacketDefaultTypeInternal protomessage::_ProtoPacket_default_instance_
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT ProtoPacket_HandshakeDefaultTypeInternal protomessage::_ProtoPacket_Handshake_default_instance_
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT ProtoPacket_OnionBodyDefaultTypeInternal protomessage::_ProtoPacket_OnionBody_default_instance_
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT ProtoPacket_OnionHeadDefaultTypeInternal protomessage::_ProtoPacket_OnionHead_default_instance_
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_proto_2dpacket_2eproto
::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_proto_2dpacket_2eproto_once
const ::PROTOBUF_NAMESPACE_ID::Message *const file_default_instances []
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const ** file_level_enum_descriptors_proto_2dpacket_2eproto = nullptr
::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_proto_2dpacket_2eproto [4]
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const ** file_level_service_descriptors_proto_2dpacket_2eproto = nullptr
Macro Definition Documentation
CHK_ [1/4]
#define CHK_ (x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
CHK_ [2/4]
#define CHK_ (x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
CHK_ [3/4]
#define CHK_ (x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
CHK_ [4/4]
#define CHK_ (x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
Function Documentation
Arena::CreateMaybeMessage< ::protomessage::ProtoPacket >()
template<> PROTOBUF_NOINLINE ::protomessage::ProtoPacket* Arena::CreateMaybeMessage< ::protomessage::ProtoPacket > (Arena * arena)
Definition at line 1244 of file proto-packet.pb.cc.
References Arena::CreateMaybeMessage< ::protomessage::ProtoPacket >().
Referenced by Arena::CreateMaybeMessage< ::protomessage::ProtoPacket >().
Arena::CreateMaybeMessage< ::protomessage::ProtoPacket_Handshake >()
template<> PROTOBUF_NOINLINE ::protomessage::ProtoPacket_Handshake* Arena::CreateMaybeMessage< ::protomessage::ProtoPacket_Handshake > (Arena * arena)
Definition at line 1241 of file proto-packet.pb.cc.
References Arena::CreateMaybeMessage< ::protomessage::ProtoPacket_Handshake >().
Referenced by Arena::CreateMaybeMessage< ::protomessage::ProtoPacket_Handshake >().
Arena::CreateMaybeMessage< ::protomessage::ProtoPacket_OnionBody >()
template<> PROTOBUF_NOINLINE ::protomessage::ProtoPacket_OnionBody* Arena::CreateMaybeMessage< ::protomessage::ProtoPacket_OnionBody > (Arena * arena)
Definition at line 1238 of file proto-packet.pb.cc.
References Arena::CreateMaybeMessage< ::protomessage::ProtoPacket_OnionBody >().
Referenced by Arena::CreateMaybeMessage< ::protomessage::ProtoPacket_OnionBody >().
Arena::CreateMaybeMessage< ::protomessage::ProtoPacket_OnionHead >()
template<> PROTOBUF_NAMESPACE_OPEN PROTOBUF_NOINLINE ::protomessage::ProtoPacket_OnionHead* Arena::CreateMaybeMessage< ::protomessage::ProtoPacket_OnionHead > (Arena * arena)
Definition at line 1235 of file proto-packet.pb.cc.
References Arena::CreateMaybeMessage< ::protomessage::ProtoPacket_OnionHead >().
Referenced by Arena::CreateMaybeMessage< ::protomessage::ProtoPacket_OnionHead >().
descriptor_table_proto_2dpacket_2eproto_getter()
const PROTOBUF_ATTRIBUTE_WEAK ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable* descriptor_table_proto_2dpacket_2eproto_getter ()
Definition at line 159 of file proto-packet.pb.cc.
References descriptor_table_proto_2dpacket_2eproto.
Referenced by protomessage::ProtoPacket_OnionHead::GetMetadata(), protomessage::ProtoPacket_OnionBody::GetMetadata(), protomessage::ProtoPacket_Handshake::GetMetadata(), and protomessage::ProtoPacket::GetMetadata().
PROTOBUF_SECTION_VARIABLE()
const uint32_t TableStruct_proto_2dpacket_2eproto::offsets [] PROTOBUF_SECTION_VARIABLE (protodesc_cold)
Variable Documentation
descriptor_table_proto_2dpacket_2eproto
static PROTOBUF_ATTRIBUTE_INIT_PRIORITY::PROTOBUF_NAMESPACE_ID::internal::AddDescriptorsRunner dynamic_init_dummy_proto_2dpacket_2eproto & descriptor_table_proto_2dpacket_2eproto
Initial value:
= {
  false, false, 542, descriptor_table_protodef_proto_2dpacket_2eproto, "proto-packet.proto",
  &descriptor_table_proto_2dpacket_2eproto_once, nullptr, 0, 4,
  schemas, file_default_instances, TableStruct_proto_2dpacket_2eproto::offsets,
  file_level_metadata_proto_2dpacket_2eproto, file_level_enum_descriptors_proto_2dpacket_2eproto, file_level_service_descriptors_proto_2dpacket_2eproto,
}
Definition at line 153 of file proto-packet.pb.cc.
Referenced by descriptor_table_proto_2dpacket_2eproto_getter().
descriptor_table_proto_2dpacket_2eproto_once
::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_proto_2dpacket_2eproto_once static
Definition at line 152 of file proto-packet.pb.cc.
Referenced by protomessage::ProtoPacket_OnionHead::GetMetadata(), protomessage::ProtoPacket_OnionBody::GetMetadata(), protomessage::ProtoPacket_Handshake::GetMetadata(), and protomessage::ProtoPacket::GetMetadata().
file_default_instances
const ::PROTOBUF_NAMESPACE_ID::Message* const file_default_instances[] static
Initial value:
= {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::protomessage::_ProtoPacket_OnionHead_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::protomessage::_ProtoPacket_OnionBody_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::protomessage::_ProtoPacket_Handshake_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::protomessage::_ProtoPacket_default_instance_),
}
Definition at line 129 of file proto-packet.pb.cc.
file_level_enum_descriptors_proto_2dpacket_2eproto
constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_proto_2dpacket_2eproto = nullptr static
Definition at line 75 of file proto-packet.pb.cc.
file_level_metadata_proto_2dpacket_2eproto
::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_proto_2dpacket_2eproto[4] static
Definition at line 74 of file proto-packet.pb.cc.
Referenced by protomessage::ProtoPacket_OnionHead::GetMetadata(), protomessage::ProtoPacket_OnionBody::GetMetadata(), protomessage::ProtoPacket_Handshake::GetMetadata(), and protomessage::ProtoPacket::GetMetadata().
file_level_service_descriptors_proto_2dpacket_2eproto
constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_proto_2dpacket_2eproto = nullptr static
Definition at line 76 of file proto-packet.pb.cc.